interface Service {
  service: string;
  type: string;
}

interface CareSettingOption {
  id: number;
  name: string;
  serviceId: number;
}

// Sorted systems of care
export const systemsOfCare = [
  'Planned care',
  'Unplanned care',
  'Wellness and longevity',
  'Children and young people',
  'Chronic conditions',
  'Complex, multi-morbid',
  'Palliative care and support'
];

// Sorted care settings
export const careSettings: CareSettingOption[] = [
  { id: 2, name: 'HOME', serviceId: 1 },
  { id: 1, name: 'HEALTH STATION', serviceId: 1 },
  { id: 3, name: 'AMBULATORY SERVICE CENTER', serviceId: 2 },
  { id: 4, name: 'SPECIALTY CARE CENTER', serviceId: 3 },
  { id: 5, name: 'EXTENDED CARE FACILITY', serviceId: 3 },
  { id: 6, name: 'HOSPITAL', serviceId: 4 }
];

export const servicesList: Record<number, Service[]> = {
  1: [
    { service: 'Acute & urgent care', type: 'OPD' },
    { service: 'Allied Health & Health Promotion', type: 'OPD' },
    { service: 'Chronic mental health disorders', type: 'OPD' },
    { service: 'Chronic metabolic diseases', type: 'OPD' },
    { service: 'Chronic respiratory diseases', type: 'OPD' },
    { service: 'Complex condition / Frail elderly', type: 'OPD' },
    { service: 'Maternal Care', type: 'OPD' },
    { service: 'Other chronic diseases', type: 'OPD' },
    { service: 'Paediatric care (5 to 16)', type: 'OPD' },
    { service: 'Primary dental care', type: 'OPD' },
    { service: 'Routine health checks', type: 'OPD' },
    { service: 'Well baby care (0 to 4)', type: 'OPD' },
    { service: 'Laboratory', type: 'Diagnostic' },
    { service: 'Ultrasound', type: 'Diagnostic' },
    { service: 'X-ray', type: 'Diagnostic' },
  ],
  2: [
    // OPD Services
    { service: 'Allergy and Immunology', type: 'OPD' },
    { service: 'Anesthesiology', type: 'OPD' },
    { service: 'Cardiac Catheterization Lab', type: 'OPD' },
    { service: 'Cardiology', type: 'OPD' },
    { service: 'Cardiothoracic & Cardiovascular Surgery', type: 'OPD' },
    { service: 'Chemotherapy', type: 'OPD' },
    { service: 'Critical Care Medicine', type: 'OPD' },
    { service: 'Dentistry', type: 'OPD' },
    { service: 'Dermatology', type: 'OPD' },
    { service: 'Dialysis', type: 'OPD' },
    { service: 'Elderly Care / Geriatrics', type: 'OPD' },
    { service: 'Endocrinology', type: 'OPD' },
    { service: 'Gastroenterology', type: 'OPD' },
    { service: 'General Surgery', type: 'OPD' },
    { service: 'Haematology', type: 'OPD' },
    { service: 'Hospice and Palliative Care', type: 'OPD' },
    { service: 'Infectious Diseases', type: 'OPD' },
    { service: 'Internal Medicine', type: 'OPD' },
    { service: 'Major Emergency', type: 'OPD' },
    { service: 'Medical Genetics', type: 'OPD' },
    { service: 'Minor Emergency', type: 'OPD' },
    { service: 'Nephrology', type: 'OPD' },
    { service: 'Neurology (inc. neurophysiology and neuropathology)', type: 'OPD' },
    { service: 'Neurosurgery', type: 'OPD' },
    { service: 'Nuclear Medicine', type: 'OPD' },
    { service: 'Obstetrics & Gynaecology', type: 'OPD' },
    { service: 'Oncology', type: 'OPD' },
    { service: 'Ophthalmology', type: 'OPD' },
    { service: 'Orthopaedics (inc. podiatry)', type: 'OPD' },
    { service: 'Otolaryngology / ENT', type: 'OPD' },
    { service: 'Paediatric Medicine', type: 'OPD' },
    { service: 'Paediatric Surgery', type: 'OPD' },
    { service: 'Physical Medicine and Rehabilitation', type: 'OPD' },
    { service: 'Plastics (incl. Burns and Maxillofacial)', type: 'OPD' },
    { service: 'Psychiatry', type: 'OPD' },
    { service: 'Pulmonology / Respiratory Medicine', type: 'OPD' },
    { service: 'Rheumatology', type: 'OPD' },
    { service: 'Sexual & Reproductive Health / Genitourinary Medicine (GUM)', type: 'OPD' },
    { service: 'Social, Community and Preventative Medicine', type: 'OPD' },
    { service: 'Trauma and Emergency Medicine', type: 'OPD' },
    { service: 'Urology', type: 'OPD' },
    { service: 'Vascular Surgery', type: 'OPD' },
    // Treatment Services
    { service: 'LINAC', type: 'Treatment' },
    // Diagnostic Services
    { service: 'CT-scans', type: 'Diagnostic' },
    { service: 'Endoscopy', type: 'Diagnostic' },
    { service: 'Laboratory', type: 'Diagnostic' },
    { service: 'MRI scans', type: 'Diagnostic' },
    { service: 'PET scans', type: 'Diagnostic' },
    { service: 'Ultrasound', type: 'Diagnostic' },
    { service: 'X-ray', type: 'Diagnostic' },
    { service: 'Fluoroscopy Imaging', type: 'Diagnostic' },
    { service: 'Nuclear Medicine Imaging', type: 'Diagnostic' }
  ],
  3: [
    // Emergency Services
    { service: 'Major Emergency', type: 'OPD' },
    { service: 'Minor Emergency', type: 'OPD' },
    // Inpatient Services
    { service: 'General Surgery', type: 'Inpatient' },
    { service: 'Urology', type: 'Inpatient' },
    { service: 'Vascular Surgery', type: 'Inpatient' },
    { service: 'Otolaryngology / ENT', type: 'Inpatient' },
    { service: 'Ophthalmology', type: 'Inpatient' },
    { service: 'Dentistry', type: 'Inpatient' },
    { service: 'Neurology (inc. neurophysiology and neuropathology)', type: 'Inpatient' },
    { service: 'Plastics (incl. Burns and Maxillofacial)', type: 'Inpatient' },
    { service: 'Paediatric Surgery', type: 'Inpatient' },
    { service: 'Trauma and Emergency Medicine', type: 'Inpatient' },
    { service: 'Critical Care Medicine', type: 'Inpatient' },
    { service: 'Gastroenterology', type: 'Inpatient' },
    { service: 'Endocrinology', type: 'Inpatient' },
    { service: 'Haematology', type: 'Inpatient' },
    { service: 'Neurosurgery', type: 'Inpatient' },
    { service: 'Cardiothoracic & Cardiovascular Surgery', type: 'Inpatient' },
    { service: 'Internal Medicine', type: 'Inpatient' },
    { service: 'Allergy and Immunology', type: 'Inpatient' },
    { service: 'Physical Medicine and Rehabilitation', type: 'Inpatient' },
    { service: 'Hospice and Palliative Care', type: 'Inpatient' },
    { service: 'Cardiology', type: 'Inpatient' },
    { service: 'Paediatric Medicine', type: 'Inpatient' },
    { service: 'Dermatology', type: 'Inpatient' },
    { service: 'Pulmonology / Respiratory Medicine', type: 'Inpatient' },
    { service: 'Infectious Diseases', type: 'Inpatient' },
    { service: 'Sexual & Reproductive Health / Genitourinary Medicine (GUM)', type: 'Inpatient' },
    { service: 'Nephrology', type: 'Inpatient' },
    { service: 'Oncology', type: 'Inpatient' },
    { service: 'Rheumatology', type: 'Inpatient' },
    { service: 'Elderly Care / Geriatrics', type: 'Inpatient' },
    { service: 'Obstetrics & Gynaecology', type: 'Inpatient' },
    { service: 'Psychiatry', type: 'Inpatient' },
    { service: 'Diagnostics & Therapeutics', type: 'Inpatient' },
    { service: 'Other', type: 'Inpatient' },
    { service: 'Orthopaedics (inc. podiatry)', type: 'Inpatient' },
    { service: 'Skilled Nursing', type: 'Inpatient' },
    // OPD Services
    { service: 'General Surgery', type: 'OPD' },
    { service: 'Urology', type: 'OPD' },
    { service: 'Vascular Surgery', type: 'OPD' },
    { service: 'Otolaryngology / ENT', type: 'OPD' },
    { service: 'Ophthalmology', type: 'OPD' },
    { service: 'Dentistry', type: 'OPD' },
    { service: 'Plastics (incl. Burns and Maxillofacial)', type: 'OPD' },
    { service: 'Paediatric Surgery', type: 'OPD' },
    { service: 'Trauma and Emergency Medicine', type: 'OPD' },
    { service: 'Anesthesiology', type: 'OPD' },
    { service: 'Critical Care Medicine', type: 'OPD' },
    { service: 'Gastroenterology', type: 'OPD' },
    { service: 'Endocrinology', type: 'OPD' },
    { service: 'Haematology', type: 'OPD' },
    { service: 'Medical Genetics', type: 'OPD' },
    { service: 'Neurosurgery', type: 'OPD' },
    { service: 'Cardiothoracic & Cardiovascular Surgery', type: 'OPD' },
    { service: 'Internal Medicine', type: 'OPD' },
    { service: 'Allergy and Immunology', type: 'OPD' },
    { service: 'Physical Medicine and Rehabilitation', type: 'OPD' },
    { service: 'Hospice and Palliative Care', type: 'OPD' },
    { service: 'Cardiology', type: 'OPD' },
    { service: 'Paediatric Medicine', type: 'OPD' },
    { service: 'Dermatology', type: 'OPD' },
    { service: 'Pulmonology / Respiratory Medicine', type: 'OPD' },
    { service: 'Infectious Diseases', type: 'OPD' },
    { service: 'Sexual & Reproductive Health / Genitourinary Medicine (GUM)', type: 'OPD' },
    { service: 'Nephrology', type: 'OPD' },
    { service: 'Oncology', type: 'OPD' },
    { service: 'Nuclear Medicine', type: 'OPD' },
    { service: 'Neurology (inc. neurophysiology and neuropathology)', type: 'OPD' },
    { service: 'Rheumatology', type: 'OPD' },
    { service: 'Elderly Care / Geriatrics', type: 'OPD' },
    { service: 'Obstetrics & Gynaecology', type: 'OPD' },
    { service: 'Psychiatry', type: 'OPD' },
    { service: 'Social, Community and Preventative Medicine', type: 'OPD' },
    { service: 'Other', type: 'OPD' },
    { service: 'Orthopaedics (inc. podiatry)', type: 'OPD' },
    // Diagnostic/Therapeutic Services
    { service: 'Dialysis', type: 'Diagnostic/Therapeutic' },
    { service: 'Chemotherapy', type: 'Diagnostic/Therapeutic' },
    { service: 'LINAC', type: 'Diagnostic/Therapeutic' },
    { service: 'X-ray', type: 'Diagnostic/Therapeutic' },
    { service: 'CT-scans', type: 'Diagnostic/Therapeutic' },
    { service: 'MRI scans', type: 'Diagnostic/Therapeutic' },
    { service: 'PET scans', type: 'Diagnostic/Therapeutic' },
    { service: 'Endoscopy', type: 'Diagnostic/Therapeutic' },
    { service: 'Cardiac catheterization lab', type: 'Diagnostic/Therapeutic' },
    { service: 'Nuclear Medicine Imaging', type: 'Diagnostic/Therapeutic' },
    { service: 'Ultrasound', type: 'Diagnostic/Therapeutic' },
    { service: 'Fluoroscopy Imaging', type: 'Diagnostic/Therapeutic' },
    { service: 'Laboratory', type: 'Diagnostic/Therapeutic' }
  ],
  4: [
    // Hospital Services
    { service: 'Major Emergency', type: 'Emergency' },
    { service: 'Minor Emergency', type: 'Emergency' },
    { service: 'Critical Care Medicine', type: 'Critical Care' },
    { service: 'General Surgery', type: 'Surgery' },
    { service: 'Cardiothoracic & Cardiovascular Surgery', type: 'Surgery' },
    { service: 'Neurosurgery', type: 'Surgery' },
    { service: 'Orthopaedics (inc. podiatry)', type: 'Surgery' },
    { service: 'Plastics (incl. Burns and Maxillofacial)', type: 'Surgery' },
    { service: 'Trauma and Emergency Medicine', type: 'Emergency' },
    { service: 'Cardiology', type: 'Medicine' },
    { service: 'Endocrinology', type: 'Medicine' },
    { service: 'Gastroenterology', type: 'Medicine' },
    { service: 'Haematology', type: 'Medicine' },
    { service: 'Infectious Diseases', type: 'Medicine' },
    { service: 'Internal Medicine', type: 'Medicine' },
    { service: 'Nephrology', type: 'Medicine' },
    { service: 'Neurology (inc. neurophysiology and neuropathology)', type: 'Medicine' },
    { service: 'Oncology', type: 'Medicine' },
    { service: 'Pulmonology / Respiratory Medicine', type: 'Medicine' },
    { service: 'Rheumatology', type: 'Medicine' },
    // Diagnostic Services
    { service: 'Laboratory', type: 'Diagnostic' },
    { service: 'Radiology', type: 'Diagnostic' },
    { service: 'Nuclear Medicine', type: 'Diagnostic' },
    { service: 'Pathology', type: 'Diagnostic' }
  ]
};