INSERT INTO home_services_mapping 
(icd_code, service, confidence, mapping_logic, systems_of_care) 
VALUES
  -- Primary dental care (50 codes)
  ('K00.0', 'Primary dental care', 'high', 'Anodontia requires regular dental monitoring', 'Planned care'),
  ('K00.1', 'Primary dental care', 'high', 'Supernumerary teeth need dental assessment', 'Planned care'),
  ('K00.2', 'Primary dental care', 'high', 'Abnormalities of size and form of teeth', 'Planned care'),
  ('K00.3', 'Primary dental care', 'high', 'Mottled teeth require dental care', 'Planned care'),
  ('K00.4', 'Primary dental care', 'high', 'Disturbances in tooth formation', 'Planned care'),
  ('K00.5', 'Primary dental care', 'high', 'Hereditary disturbances in tooth structure', 'Planned care'),
  ('K00.6', 'Primary dental care', 'high', 'Disturbances in tooth eruption', 'Planned care'),
  ('K00.7', 'Primary dental care', 'high', 'Teething syndrome needs monitoring', 'Planned care'),
  ('K00.8', 'Primary dental care', 'high', 'Other disorders of tooth development', 'Planned care'),
  ('K00.9', 'Primary dental care', 'high', 'Disorder of tooth development, unspecified', 'Planned care'),
  ('K01.0', 'Primary dental care', 'high', 'Embedded teeth require assessment', 'Planned care'),
  ('K01.1', 'Primary dental care', 'high', 'Impacted teeth need monitoring', 'Planned care'),
  ('K02.3', 'Primary dental care', 'high', 'Arrested dental caries', 'Planned care'),
  ('K02.51', 'Primary dental care', 'high', 'Dental caries on pit and fissure surface', 'Planned care'),
  ('K02.52', 'Primary dental care', 'high', 'Dental caries on smooth surface', 'Planned care'),
  ('K02.53', 'Primary dental care', 'high', 'Dental caries on root surface', 'Planned care'),
  ('K02.61', 'Primary dental care', 'high', 'Dental caries pit and fissure penetrating into dentin', 'Planned care'),
  ('K02.62', 'Primary dental care', 'high', 'Dental caries on smooth surface penetrating into dentin', 'Planned care'),
  ('K02.63', 'Primary dental care', 'high', 'Dental caries on root surface penetrating into dentin', 'Planned care'),
  ('K02.7', 'Primary dental care', 'high', 'Dental caries extending into pulp', 'Planned care'),
  ('K02.9', 'Primary dental care', 'high', 'Dental caries, unspecified', 'Planned care'),
  ('K03.0', 'Primary dental care', 'high', 'Excessive attrition of teeth', 'Planned care'),
  ('K03.1', 'Primary dental care', 'high', 'Abrasion of teeth needs monitoring', 'Planned care'),
  ('K03.2', 'Primary dental care', 'high', 'Erosion of teeth requires care', 'Planned care'),
  ('K03.3', 'Primary dental care', 'high', 'Pathological resorption of teeth', 'Planned care'),
  ('K03.4', 'Primary dental care', 'high', 'Hypercementosis needs assessment', 'Planned care'),
  ('K03.5', 'Primary dental care', 'high', 'Ankylosis of teeth requires monitoring', 'Planned care'),
  ('K03.6', 'Primary dental care', 'high', 'Deposits [accretions] on teeth', 'Planned care'),
  ('K03.7', 'Primary dental care', 'high', 'Posteruptive color changes of dental hard tissues', 'Planned care'),
  ('K03.81', 'Primary dental care', 'high', 'Cracked tooth needs assessment', 'Planned care'),
  ('K03.89', 'Primary dental care', 'high', 'Other specified diseases of hard tissues of teeth', 'Planned care'),
  ('K03.9', 'Primary dental care', 'high', 'Disease of hard tissues of teeth, unspecified', 'Planned care'),
  ('K04.0', 'Primary dental care', 'high', 'Pulpitis requires dental care', 'Planned care'),
  ('K04.1', 'Primary dental care', 'high', 'Necrosis of pulp needs treatment', 'Planned care'),
  ('K04.2', 'Primary dental care', 'high', 'Pulp degeneration requires care', 'Planned care'),
  ('K04.3', 'Primary dental care', 'high', 'Abnormal hard tissue formation in pulp', 'Planned care'),
  ('K04.4', 'Primary dental care', 'high', 'Acute apical periodontitis of pulpal origin', 'Planned care'),
  ('K04.5', 'Primary dental care', 'high', 'Chronic apical periodontitis needs monitoring', 'Planned care'),
  ('K04.6', 'Primary dental care', 'high', 'Periapical abscess with sinus', 'Planned care'),
  ('K04.7', 'Primary dental care', 'high', 'Periapical abscess without sinus', 'Planned care'),
  ('K04.8', 'Primary dental care', 'high', 'Radicular cyst requires treatment', 'Planned care'),
  ('K04.90', 'Primary dental care', 'high', 'Unspecified diseases of pulp and periapical tissues', 'Planned care'),
  ('K04.99', 'Primary dental care', 'high', 'Other diseases of pulp and periapical tissues', 'Planned care'),
  ('K05.00', 'Primary dental care', 'high', 'Acute gingivitis, plaque induced', 'Planned care'),
  ('K05.01', 'Primary dental care', 'high', 'Acute gingivitis, non-plaque induced', 'Planned care'),
  ('K05.10', 'Primary dental care', 'high', 'Chronic gingivitis, plaque induced', 'Planned care'),
  ('K05.11', 'Primary dental care', 'high', 'Chronic gingivitis, non-plaque induced', 'Planned care'),
  ('K05.20', 'Primary dental care', 'high', 'Aggressive periodontitis, unspecified', 'Planned care'),
  ('K05.21', 'Primary dental care', 'high', 'Aggressive periodontitis, localized', 'Planned care'),
  ('K05.22', 'Primary dental care', 'high', 'Aggressive periodontitis, generalized', 'Planned care'),

  -- Routine health checks (50 codes)
  ('Z00.110', 'Routine health checks', 'high', 'Health supervision for newborn under 8 days old', 'Wellness and longevity'),
  ('Z00.111', 'Routine health checks', 'high', 'Health supervision for newborn 8 to 28 days old', 'Wellness and longevity'),
  ('Z00.121', 'Routine health checks', 'high', 'Encounter for routine child health examination with abnormal findings', 'Wellness and longevity'),
  ('Z00.129', 'Routine health checks', 'high', 'Encounter for routine child health examination without abnormal findings', 'Wellness and longevity'),
  ('Z00.5', 'Routine health checks', 'high', 'Encounter for examination of potential donor of organ and tissue', 'Wellness and longevity'),
  ('Z00.6', 'Routine health checks', 'high', 'Encounter for examination for normal comparison and control in clinical research program', 'Wellness and longevity'),
  ('Z00.70', 'Routine health checks', 'high', 'Encounter for examination for period of delayed growth in childhood without abnormal findings', 'Wellness and longevity'),
  ('Z00.71', 'Routine health checks', 'high', 'Encounter for examination for period of delayed growth in childhood with abnormal findings', 'Wellness and longevity'),
  ('Z00.8', 'Routine health checks', 'high', 'Encounter for other general examination', 'Wellness and longevity'),
  ('Z01.00', 'Routine health checks', 'high', 'Encounter for examination of eyes and vision without abnormal findings', 'Wellness and longevity'),
  ('Z01.01', 'Routine health checks', 'high', 'Encounter for examination of eyes and vision with abnormal findings', 'Wellness and longevity'),
  ('Z01.10', 'Routine health checks', 'high', 'Encounter for examination of ears and hearing without abnormal findings', 'Wellness and longevity'),
  ('Z01.110', 'Routine health checks', 'high', 'Encounter for hearing examination following failed hearing screening', 'Wellness and longevity'),
  ('Z01.118', 'Routine health checks', 'high', 'Encounter for examination of ears and hearing with other abnormal findings', 'Wellness and longevity'),
  ('Z01.12', 'Routine health checks', 'high', 'Encounter for hearing conservation and treatment', 'Wellness and longevity'),
  ('Z01.20', 'Routine health checks', 'high', 'Encounter for dental examination and cleaning without abnormal findings', 'Wellness and longevity'),
  ('Z01.21', 'Routine health checks', 'high', 'Encounter for dental examination and cleaning with abnormal findings', 'Wellness and longevity'),
  ('Z01.30', 'Routine health checks', 'high', 'Encounter for examination of blood pressure without abnormal findings', 'Wellness and longevity'),
  ('Z01.31', 'Routine health checks', 'high', 'Encounter for examination of blood pressure with abnormal findings', 'Wellness and longevity'),
  ('Z01.411', 'Routine health checks', 'high', 'Encounter for gynecological examination (general) (routine) with abnormal findings', 'Wellness and longevity'),
  ('Z01.419', 'Routine health checks', 'high', 'Encounter for gynecological examination (general) (routine) without abnormal findings', 'Wellness and longevity'),
  ('Z01.42', 'Routine health checks', 'high', 'Encounter for cervical smear to confirm findings of recent normal smear following initial abnormal smear', 'Wellness and longevity'),
  ('Z01.810', 'Routine health checks', 'high', 'Encounter for preprocedural cardiovascular examination', 'Wellness and longevity'),
  ('Z01.811', 'Routine health checks', 'high', 'Encounter for preprocedural respiratory examination', 'Wellness and longevity'),
  ('Z01.812', 'Routine health checks', 'high', 'Encounter for preprocedural laboratory examination', 'Wellness and longevity'),
  ('Z01.818', 'Routine health checks', 'high', 'Encounter for other preprocedural examination', 'Wellness and longevity'),
  ('Z01.82', 'Routine health checks', 'high', 'Encounter for allergy testing', 'Wellness and longevity'),
  ('Z01.83', 'Routine health checks', 'high', 'Encounter for blood typing', 'Wellness and longevity'),
  ('Z01.84', 'Routine health checks', 'high', 'Encounter for antibody response examination', 'Wellness and longevity'),
  ('Z01.89', 'Routine health checks', 'high', 'Encounter for other specified special examinations', 'Wellness and longevity'),
  ('Z02.0', 'Routine health checks', 'high', 'Encounter for examination for admission to educational institution', 'Wellness and longevity'),
  ('Z02.1', 'Routine health checks', 'high', 'Encounter for pre-employment examination', 'Wellness and longevity'),
  ('Z02.2', 'Routine health checks', 'high', 'Encounter for examination for admission to residential institution', 'Wellness and longevity'),
  ('Z02.3', 'Routine health checks', 'high', 'Encounter for examination for recruitment to armed forces', 'Wellness and longevity'),
  ('Z02.4', 'Routine health checks', 'high', 'Encounter for examination for driving license', 'Wellness and longevity'),
  ('Z02.5', 'Routine health checks', 'high', 'Encounter for examination for participation in sport', 'Wellness and longevity'),
  ('Z02.6', 'Routine health checks', 'high', 'Encounter for examination for insurance purposes', 'Wellness and longevity'),
  ('Z02.71', 'Routine health checks', 'high', 'Encounter for disability determination', 'Wellness and longevity'),
  ('Z02.79', 'Routine health checks', 'high', 'Encounter for issue of other medical certificate', 'Wellness and longevity'),
  ('Z02.81', 'Routine health checks', 'high', 'Encounter for paternity testing', 'Wellness and longevity'),
  ('Z02.82', 'Routine health checks', 'high', 'Encounter for adoption services', 'Wellness and longevity'),
  ('Z02.83', 'Routine health checks', 'high', 'Encounter for blood-alcohol and blood-drug test', 'Wellness and longevity'),
  ('Z02.89', 'Routine health checks', 'high', 'Encounter for other administrative examinations', 'Wellness and longevity'),
  ('Z02.9', 'Routine health checks', 'high', 'Encounter for administrative examinations, unspecified', 'Wellness and longevity'),
  ('Z03.6', 'Routine health checks', 'high', 'Encounter for observation for suspected toxic effect from ingested substance ruled out', 'Wellness and longevity'),
  ('Z03.71', 'Routine health checks', 'high', 'Encounter for suspected problem with amniotic cavity and membrane ruled out', 'Wellness and longevity'),
  ('Z03.72', 'Routine health checks', 'high', 'Encounter for suspected placental problem ruled out', 'Wellness and longevity'),
  ('Z03.73', 'Routine health checks', 'high', 'Encounter for suspected fetal anomaly ruled out', 'Wellness and longevity'),
  ('Z03.74', 'Routine health checks', 'high', 'Encounter for suspected problem with fetal growth ruled out', 'Wellness and longevity'),
  ('Z03.75', 'Routine health checks', 'high', 'Encounter for suspected cervical shortening ruled out', 'Wellness and longevity'),

  -- Other chronic diseases (50 codes)
  ('M05.00', 'Other chronic diseases', 'high', 'Felty syndrome, unspecified site', 'Chronic conditions'),
  ('M05.011', 'Other chronic diseases', 'high', 'Felty syndrome, right shoulder', 'Chronic conditions'),
  ('M05.012', 'Other chronic diseases', 'high', 'Felty syndrome, left shoulder', 'Chronic conditions'),
  ('M05.019', 'Other chronic diseases', 'high', 'Felty syndrome, unspecified shoulder', 'Chronic conditions'),
  ('M05.021', 'Other chronic diseases', 'high', 'Felty syndrome, right elbow', 'Chronic conditions'),
  ('M05.022', 'Other chronic diseases', 'high', 'Felty syndrome, left elbow', 'Chronic conditions'),
  ('M05.029', 'Other chronic diseases', 'high', 'Felty syndrome, unspecified elbow', 'Chronic conditions'),
  ('M05.031', 'Other chronic diseases', 'high', 'Felty syndrome, right wrist', 'Chronic conditions'),
  ('M05.032', 'Other chronic diseases', 'high', 'Felty syndrome, left wrist', 'Chronic conditions'),
  ('M05.039', 'Other chronic diseases', 'high', 'Felty syndrome, unspecified wrist', 'Chronic conditions'),
  ('M05.041', 'Other chronic diseases', 'high', 'Felty syndrome, right hand', 'Chronic conditions'),
  ('M05.042', 'Other chronic diseases', 'high', 'Felty syndrome, left hand', 'Chronic conditions'),
  ('M05.049', 'Other chronic diseases', 'high', 'Felty syndrome, unspecified hand', 'Chronic conditions'),
  ('M05.051', 'Other chronic diseases', 'high', 'Felty syndrome, right hip', 'Chronic conditions'),
  ('M05.052', 'Other chronic diseases', 'high', 'Felty syndrome, left hip', 'Chronic conditions'),
  ('M05.059', 'Other chronic diseases', 'high', 'Felty syndrome, unspecified hip', 'Chronic conditions'),
  ('M05.061', 'Other chronic diseases', 'high', 'Felty syndrome, right knee', 'Chronic conditions'),
  ('M05.062', 'Other chronic diseases', 'high', 'Felty syndrome, left knee', 'Chronic conditions'),
  ('M05.069', 'Other chronic diseases', 'high', 'Felty syndrome, unspecified knee', 'Chronic conditions'),
  ('M05.071', 'Other chronic diseases', 'high', 'Felty syndrome, right ankle and foot', 'Chronic conditions'),
  ('M05.072', 'Other chronic diseases', 'high', 'Felty syndrome, left ankle and foot', 'Chronic conditions'),
  ('M05.079', 'Other chronic diseases', 'high', 'Felty syndrome, unspecified ankle and foot', 'Chronic conditions'),
  ('M05.09', 'Other chronic diseases', 'high', 'Felty syndrome, multiple sites', 'Chronic conditions'),
  ('M05.20', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified site', 'Chronic conditions'),
  ('M05.211', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of right shoulder', 'Chronic conditions'),
  ('M05.212', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of left shoulder', 'Chronic conditions'),
  ('M05.219', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified shoulder', 'Chronic conditions'),
  ('M05.221', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of right elbow', 'Chronic conditions'),
  ('M05.222', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of left elbow', 'Chronic conditions'),
  ('M05.229', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified elbow', 'Chronic conditions'),
  ('M05.231', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of right wrist', 'Chronic conditions'),
  ('M05.232', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of left wrist', 'Chronic conditions'),
  ('M05.239', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified wrist', 'Chronic conditions'),
  ('M05.241', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of right hand', 'Chronic conditions'),
  ('M05.242', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of left hand', 'Chronic conditions'),
  ('M05.249', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified hand', 'Chronic conditions'),
  ('M05.251', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of right hip', 'Chronic conditions'),
  ('M05.252', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of left hip', 'Chronic conditions'),
  ('M05.259', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified hip', 'Chronic conditions'),
  ('M05.261', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of right knee', 'Chronic conditions'),
  ('M05.262', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of left knee', 'Chronic conditions'),
  ('M05.269', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified knee', 'Chronic conditions'),
  ('M05.271', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of right ankle and foot', 'Chronic conditions'),
  ('M05.272', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of left ankle and foot', 'Chronic conditions'),
  ('M05.279', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified ankle and foot', 'Chronic conditions'),
  ('M05.29', 'Other chronic diseases', 'high', 'Rheumatoid vasculitis with rheumatoid arthritis of multiple sites', 'Chronic conditions'),
  ('M05.30', 'Other chronic diseases', 'high', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified site', 'Chronic conditions'),
  ('M05.311', 'Other chronic diseases', 'high', 'Rheumatoid heart disease with rheumatoid arthritis of right shoulder', 'Chronic conditions'),
  ('M05.312', 'Other chronic diseases', 'high', 'Rheumatoid heart disease with rheumatoid arthritis of left shoulder', 'Chronic conditions'),
  ('M05.319', 'Other chronic diseases', 'high', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified shoulder', 'Chronic conditions'),
  ('M05.321', 'Other chronic diseases', 'high', 'Rheumatoid heart disease with rheumatoid arthritis of right elbow', 'Chronic conditions');

-- Add corresponding entries to home_codes if they don't exist
INSERT INTO home_codes ("Care Setting", "Systems of Care", "ICD FamilyCode")
SELECT 
    'HOME',
    systems_of_care,
    icd_code
FROM home_services_mapping
WHERE NOT EXISTS (
    SELECT 1 FROM home_codes WHERE "ICD FamilyCode" = home_services_mapping.icd_code
)
ON CONFLICT DO NOTHING;