INSERT INTO home_services_mapping 
(icd_code, service, confidence, mapping_logic, systems_of_care) 
VALUES
  -- Chronic respiratory diseases (100 codes)
  ('J97.0', 'Chronic respiratory diseases', 'high', 'Tracheostomy complications', 'Chronic conditions'),
  ('J97.1', 'Chronic respiratory diseases', 'high', 'Other postprocedural respiratory disorders', 'Chronic conditions'),
  ('J97.2', 'Chronic respiratory diseases', 'high', 'Acute and chronic respiratory failure following thoracic surgery', 'Chronic conditions'),
  ('J97.3', 'Chronic respiratory diseases', 'high', 'Chronic pulmonary insufficiency following surgery', 'Chronic conditions'),
  ('J98.01', 'Chronic respiratory diseases', 'high', 'Acute bronchospasm', 'Chronic conditions'),
  ('J98.09', 'Chronic respiratory diseases', 'high', 'Other diseases of bronchus, not elsewhere classified', 'Chronic conditions'),
  ('J98.11', 'Chronic respiratory diseases', 'high', 'Atelectasis', 'Chronic conditions'),
  ('J98.19', 'Chronic respiratory diseases', 'high', 'Other pulmonary collapse', 'Chronic conditions'),
  ('J98.2', 'Chronic respiratory diseases', 'high', 'Interstitial emphysema', 'Chronic conditions'),
  ('J98.3', 'Chronic respiratory diseases', 'high', 'Compensatory emphysema', 'Chronic conditions'),
  ('J98.4', 'Chronic respiratory diseases', 'high', 'Other disorders of lung', 'Chronic conditions'),
  ('J98.51', 'Chronic respiratory diseases', 'high', 'Mediastinitis', 'Chronic conditions'),
  ('J98.59', 'Chronic respiratory diseases', 'high', 'Other diseases of mediastinum, not elsewhere classified', 'Chronic conditions'),
  ('J98.6', 'Chronic respiratory diseases', 'high', 'Disorders of diaphragm', 'Chronic conditions'),
  ('J98.8', 'Chronic respiratory diseases', 'high', 'Other specified respiratory disorders', 'Chronic conditions'),
  ('J98.9', 'Chronic respiratory diseases', 'high', 'Respiratory disorder, unspecified', 'Chronic conditions'),
  ('J99', 'Chronic respiratory diseases', 'high', 'Respiratory disorders in diseases classified elsewhere', 'Chronic conditions'),
  ('J80', 'Chronic respiratory diseases', 'high', 'Acute respiratory distress syndrome', 'Chronic conditions'),
  ('J81.0', 'Chronic respiratory diseases', 'high', 'Acute pulmonary edema', 'Chronic conditions'),
  ('J81.1', 'Chronic respiratory diseases', 'high', 'Chronic pulmonary edema', 'Chronic conditions'),
  ('J82.81', 'Chronic respiratory diseases', 'high', 'Chronic eosinophilic pneumonia', 'Chronic conditions'),
  ('J82.82', 'Chronic respiratory diseases', 'high', 'Acute eosinophilic pneumonia', 'Chronic conditions'),
  ('J82.83', 'Chronic respiratory diseases', 'high', 'Eosinophilic asthma', 'Chronic conditions'),
  ('J82.89', 'Chronic respiratory diseases', 'high', 'Other pulmonary eosinophilia, not elsewhere classified', 'Chronic conditions'),
  ('J84.01', 'Chronic respiratory diseases', 'high', 'Alveolar proteinosis', 'Chronic conditions'),
  ('J84.02', 'Chronic respiratory diseases', 'high', 'Pulmonary alveolar microlithiasis', 'Chronic conditions'),
  ('J84.03', 'Chronic respiratory diseases', 'high', 'Idiopathic pulmonary hemosiderosis', 'Chronic conditions'),
  ('J84.09', 'Chronic respiratory diseases', 'high', 'Other alveolar and parietoalveolar conditions', 'Chronic conditions'),
  ('J84.10', 'Chronic respiratory diseases', 'high', 'Pulmonary fibrosis, unspecified', 'Chronic conditions'),
  ('J84.111', 'Chronic respiratory diseases', 'high', 'Idiopathic interstitial pneumonia, not otherwise specified', 'Chronic conditions'),
  ('J84.112', 'Chronic respiratory diseases', 'high', 'Idiopathic pulmonary fibrosis', 'Chronic conditions'),
  ('J84.113', 'Chronic respiratory diseases', 'high', 'Idiopathic non-specific interstitial pneumonitis', 'Chronic conditions'),
  ('J84.114', 'Chronic respiratory diseases', 'high', 'Acute interstitial pneumonitis', 'Chronic conditions'),
  ('J84.115', 'Chronic respiratory diseases', 'high', 'Respiratory bronchiolitis interstitial lung disease', 'Chronic conditions'),
  ('J84.116', 'Chronic respiratory diseases', 'high', 'Cryptogenic organizing pneumonia', 'Chronic conditions'),
  ('J84.117', 'Chronic respiratory diseases', 'high', 'Desquamative interstitial pneumonia', 'Chronic conditions'),
  ('J84.17', 'Chronic respiratory diseases', 'high', 'Other interstitial pulmonary diseases with fibrosis in diseases classified elsewhere', 'Chronic conditions'),
  ('J84.2', 'Chronic respiratory diseases', 'high', 'Lymphoid interstitial pneumonia', 'Chronic conditions'),
  ('J84.81', 'Chronic respiratory diseases', 'high', 'Lymphangioleiomyomatosis', 'Chronic conditions'),
  ('J84.82', 'Chronic respiratory diseases', 'high', 'Adult pulmonary Langerhans cell histiocytosis', 'Chronic conditions'),
  ('J84.83', 'Chronic respiratory diseases', 'high', 'Surfactant mutations of the lung', 'Chronic conditions'),
  ('J84.841', 'Chronic respiratory diseases', 'high', 'Neuroendocrine cell hyperplasia of infancy', 'Chronic conditions'),
  ('J84.842', 'Chronic respiratory diseases', 'high', 'Pulmonary interstitial glycogenosis', 'Chronic conditions'),
  ('J84.843', 'Chronic respiratory diseases', 'high', 'Alveolar capillary dysplasia with vein misalignment', 'Chronic conditions'),
  ('J84.848', 'Chronic respiratory diseases', 'high', 'Other interstitial lung diseases of childhood', 'Chronic conditions'),
  ('J84.89', 'Chronic respiratory diseases', 'high', 'Other specified interstitial pulmonary diseases', 'Chronic conditions'),
  ('J84.9', 'Chronic respiratory diseases', 'high', 'Interstitial pulmonary disease, unspecified', 'Chronic conditions'),
  ('J85.0', 'Chronic respiratory diseases', 'high', 'Gangrene and necrosis of lung', 'Chronic conditions'),
  ('J85.1', 'Chronic respiratory diseases', 'high', 'Abscess of lung with pneumonia', 'Chronic conditions'),
  ('J85.2', 'Chronic respiratory diseases', 'high', 'Abscess of lung without pneumonia', 'Chronic conditions'),
  ('J85.3', 'Chronic respiratory diseases', 'high', 'Abscess of mediastinum', 'Chronic conditions'),
  ('J86.0', 'Chronic respiratory diseases', 'high', 'Pyothorax with fistula', 'Chronic conditions'),
  ('J86.9', 'Chronic respiratory diseases', 'high', 'Pyothorax without fistula', 'Chronic conditions'),
  ('J90', 'Chronic respiratory diseases', 'high', 'Pleural effusion, not elsewhere classified', 'Chronic conditions'),
  ('J91.0', 'Chronic respiratory diseases', 'high', 'Malignant pleural effusion', 'Chronic conditions'),
  ('J91.8', 'Chronic respiratory diseases', 'high', 'Pleural effusion in other conditions classified elsewhere', 'Chronic conditions'),
  ('J92.0', 'Chronic respiratory diseases', 'high', 'Pleural plaque with presence of asbestos', 'Chronic conditions'),
  ('J92.9', 'Chronic respiratory diseases', 'high', 'Pleural plaque without asbestos', 'Chronic conditions'),
  ('J93.0', 'Chronic respiratory diseases', 'high', 'Spontaneous tension pneumothorax', 'Chronic conditions'),
  ('J93.11', 'Chronic respiratory diseases', 'high', 'Primary spontaneous pneumothorax', 'Chronic conditions'),
  ('J93.12', 'Chronic respiratory diseases', 'high', 'Secondary spontaneous pneumothorax', 'Chronic conditions'),
  ('J93.81', 'Chronic respiratory diseases', 'high', 'Chronic pneumothorax', 'Chronic conditions'),
  ('J93.82', 'Chronic respiratory diseases', 'high', 'Other air leak', 'Chronic conditions'),
  ('J93.83', 'Chronic respiratory diseases', 'high', 'Other pneumothorax', 'Chronic conditions'),
  ('J93.9', 'Chronic respiratory diseases', 'high', 'Pneumothorax, unspecified', 'Chronic conditions'),
  ('J94.0', 'Chronic respiratory diseases', 'high', 'Chylous effusion', 'Chronic conditions'),
  ('J94.1', 'Chronic respiratory diseases', 'high', 'Fibrothorax', 'Chronic conditions'),
  ('J94.2', 'Chronic respiratory diseases', 'high', 'Hemothorax', 'Chronic conditions'),
  ('J94.8', 'Chronic respiratory diseases', 'high', 'Other specified pleural conditions', 'Chronic conditions'),
  ('J94.9', 'Chronic respiratory diseases', 'high', 'Pleural condition, unspecified', 'Chronic conditions'),
  ('J95.00', 'Chronic respiratory diseases', 'high', 'Unspecified tracheostomy complication', 'Chronic conditions'),
  ('J95.01', 'Chronic respiratory diseases', 'high', 'Hemorrhage from tracheostomy stoma', 'Chronic conditions'),
  ('J95.02', 'Chronic respiratory diseases', 'high', 'Infection of tracheostomy stoma', 'Chronic conditions'),
  ('J95.03', 'Chronic respiratory diseases', 'high', 'Malfunction of tracheostomy stoma', 'Chronic conditions'),
  ('J95.04', 'Chronic respiratory diseases', 'high', 'Tracheo-esophageal fistula following tracheostomy', 'Chronic conditions'),
  ('J95.09', 'Chronic respiratory diseases', 'high', 'Other tracheostomy complication', 'Chronic conditions'),
  ('J95.1', 'Chronic respiratory diseases', 'high', 'Acute pulmonary insufficiency following thoracic surgery', 'Chronic conditions'),
  ('J95.2', 'Chronic respiratory diseases', 'high', 'Acute pulmonary insufficiency following nonthoracic surgery', 'Chronic conditions'),
  ('J95.3', 'Chronic respiratory diseases', 'high', 'Chronic pulmonary insufficiency following surgery', 'Chronic conditions'),
  ('J95.4', 'Chronic respiratory diseases', 'high', 'Chemical pneumonitis due to anesthesia', 'Chronic conditions'),
  ('J95.5', 'Chronic respiratory diseases', 'high', 'Postprocedural subglottic stenosis', 'Chronic conditions'),
  ('J95.811', 'Chronic respiratory diseases', 'high', 'Postprocedural pneumothorax', 'Chronic conditions'),
  ('J95.812', 'Chronic respiratory diseases', 'high', 'Postprocedural air leak', 'Chronic conditions'),
  ('J95.821', 'Chronic respiratory diseases', 'high', 'Acute postprocedural respiratory failure', 'Chronic conditions'),
  ('J95.822', 'Chronic respiratory diseases', 'high', 'Acute and chronic postprocedural respiratory failure', 'Chronic conditions'),
  ('J95.83', 'Chronic respiratory diseases', 'high', 'Postprocedural hemorrhage of a respiratory system organ', 'Chronic conditions'),
  ('J95.84', 'Chronic respiratory diseases', 'high', 'Transfusion-related acute lung injury (TRALI)', 'Chronic conditions'),
  ('J95.851', 'Chronic respiratory diseases', 'high', 'Ventilator associated pneumonia', 'Chronic conditions'),
  ('J95.859', 'Chronic respiratory diseases', 'high', 'Other postprocedural complications', 'Chronic conditions'),
  ('J95.89', 'Chronic respiratory diseases', 'high', 'Other postprocedural complications and disorders', 'Chronic conditions'),
  ('J95.9', 'Chronic respiratory diseases', 'high', 'Postprocedural respiratory complication, unspecified', 'Chronic conditions'),
  ('J96.00', 'Chronic respiratory diseases', 'high', 'Acute respiratory failure, unspecified', 'Chronic conditions'),
  ('J96.01', 'Chronic respiratory diseases', 'high', 'Acute respiratory failure with hypoxia', 'Chronic conditions'),
  ('J96.02', 'Chronic respiratory diseases', 'high', 'Acute respiratory failure with hypercapnia', 'Chronic conditions'),
  ('J96.10', 'Chronic respiratory diseases', 'high', 'Chronic respiratory failure, unspecified', 'Chronic conditions'),
  ('J96.11', 'Chronic respiratory diseases', 'high', 'Chronic respiratory failure with hypoxia', 'Chronic conditions'),
  ('J96.12', 'Chronic respiratory diseases', 'high', 'Chronic respiratory failure with hypercapnia', 'Chronic conditions'),
  ('J96.20', 'Chronic respiratory diseases', 'high', 'Acute and chronic respiratory failure, unspecified', 'Chronic conditions'),
  ('J96.21', 'Chronic respiratory diseases', 'high', 'Acute and chronic respiratory failure with hypoxia', 'Chronic conditions'),
  ('J96.22', 'Chronic respiratory diseases', 'high', 'Acute and chronic respiratory failure with hypercapnia', 'Chronic conditions'),
  ('J96.90', 'Chronic respiratory diseases', 'high', 'Respiratory failure, unspecified, unspecified', 'Chronic conditions'),
  ('J96.91', 'Chronic respiratory diseases', 'high', 'Respiratory failure, unspecified with hypoxia', 'Chronic conditions'),
  ('J96.92', 'Chronic respiratory diseases', 'high', 'Respiratory failure, unspecified with hypercapnia', 'Chronic conditions'),
  ('J98.01', 'Chronic respiratory diseases', 'high', 'Acute bronchospasm', 'Chronic conditions'),
  ('J98.09', 'Chronic respiratory diseases', 'high', 'Other diseases of bronchus, not elsewhere classified', 'Chronic conditions'),
  ('J98.11', 'Chronic respiratory diseases', 'high', 'Atelectasis', 'Chronic conditions'),
  ('J98.19', 'Chronic respiratory diseases', 'high', 'Other pulmonary collapse', 'Chronic conditions'),

  -- Complex condition / Frail elderly (100 codes)
  ('R29.700', 'Complex condition / Frail elderly', 'high', 'NIHSS score 0', 'Complex, multi-morbid'),
  ('R29.701', 'Complex condition / Frail elderly', 'high', 'NIHSS score 1', 'Complex, multi-morbid'),
  ('R29.702', 'Complex condition / Frail elderly', 'high', 'NIHSS score 2', 'Complex, multi-morbid'),
  ('R29.703', 'Complex condition / Frail elderly', 'high', 'NIHSS score 3', 'Complex, multi-morbid'),
  ('R29.704', 'Complex condition / Frail elderly', 'high', 'NIHSS score 4', 'Complex, multi-morbid'),
  ('R29.705', 'Complex condition / Frail elderly', 'high', 'NIHSS score 5', 'Complex, multi-morbid'),
  ('R29.706', 'Complex condition / Frail elderly', 'high', 'NIHSS score 6', 'Complex, multi-morbid'),
  ('R29.707', 'Complex condition / Frail elderly', 'high', 'NIHSS score 7', 'Complex, multi-morbid'),
  ('R29.708', 'Complex condition / Frail elderly', 'high', 'NIHSS score 8', 'Complex, multi-morbid'),
  ('R29.709', 'Complex condition / Frail elderly', 'high', 'NIHSS score 9', 'Complex, multi-morbid'),
  ('R29.710', 'Complex condition / Frail elderly', 'high', 'NIHSS score 10', 'Complex, multi-morbid'),
  ('R29.711', 'Complex condition / Frail elderly', 'high', 'NIHSS score 11', 'Complex, multi-morbid'),
  ('R29.712', 'Complex condition / Frail elderly', 'high', 'NIHSS score 12', 'Complex, multi-morbid'),
  ('R29.713', 'Complex condition / Frail elderly', 'high', 'NIHSS score 13', 'Complex, multi-morbid'),
  ('R29.714', 'Complex condition / Frail elderly', 'high', 'NIHSS score 14', 'Complex, multi-morbid'),
  ('R29.715', 'Complex condition / Frail elderly', 'high', 'NIHSS score 15', 'Complex, multi-morbid'),
  ('R29.716', 'Complex condition / Frail elderly', 'high', 'NIHSS score 16', 'Complex, multi-morbid'),
  ('R29.717', 'Complex condition / Frail elderly', 'high', 'NIHSS score 17', 'Complex, multi-morbid'),
  ('R29.718', 'Complex condition / Frail elderly', 'high', 'NIHSS score 18', 'Complex, multi-morbid'),
  ('R29.719', 'Complex condition / Frail elderly', 'high', 'NIHSS score 19', 'Complex, multi-morbid'),
  ('R29.720', 'Complex condition / Frail elderly', 'high', 'NIHSS score 20', 'Complex, multi-morbid'),
  ('R29.721', 'Complex condition / Frail elderly', 'high', 'NIHSS score 21', 'Complex, multi-morbid'),
  ('R29.722', 'Complex condition / Frail elderly', 'high', 'NIHSS score 22', 'Complex, multi-morbid'),
  ('R29.723', 'Complex condition / Frail elderly', 'high', 'NIHSS score 23', 'Complex, multi-morbid'),
  ('R29.724', 'Complex condition / Frail elderly', 'high', 'NIHSS score 24', 'Complex, multi-morbid'),
  ('R29.725', 'Complex condition / Frail elderly', 'high', 'NIHSS score 25', 'Complex, multi-morbid'),
  ('R29.726', 'Complex condition / Frail elderly', 'high', 'NIHSS score 26', 'Complex, multi-morbid'),
  ('R29.727', 'Complex condition / Frail elderly', 'high', 'NIHSS score 27', 'Complex, multi-morbid'),
  ('R29.728', 'Complex condition / Frail elderly', 'high', 'NIHSS score 28', 'Complex, multi-morbid'),
  ('R29.729', 'Complex condition / Frail elderly', 'high', 'NIHSS score 29', 'Complex, multi-morbid'),
  ('R29.730', 'Complex condition / Frail elderly', 'high', 'NIHSS score 30', 'Complex, multi-morbid'),
  ('R29.731', 'Complex condition / Frail elderly', 'high', 'NIHSS score 31', 'Complex, multi-morbid'),
  ('R29.732', 'Complex condition / Frail elderly', 'high', 'NIHSS score 32', 'Complex, multi-morbid'),
  ('R29.733', 'Complex condition / Frail elderly', 'high', 'NIHSS score 33', 'Complex, multi-morbid'),
  ('R29.734', 'Complex condition / Frail elderly', 'high', 'NIHSS score 34', 'Complex, multi-morbid'),
  ('R29.735', 'Complex condition / Frail elderly', 'high', 'NIHSS score 35', 'Complex, multi-morbid'),
  ('R29.736', 'Complex condition / Frail elderly', 'high', 'NIHSS score 36', 'Complex, multi-morbid'),
  ('R29.737', 'Complex condition / Frail elderly', 'high', 'NIHSS score 37', 'Complex, multi-morbid'),
  ('R29.738', 'Complex condition / Frail elderly', 'high', 'NIHSS score 38', 'Complex, multi-morbid'),
  ('R29.739', 'Complex condition / Frail elderly', 'high', 'NIHSS score 39', 'Complex, multi-morbid'),
  ('R29.740', 'Complex condition / Frail elderly', 'high', 'NIHSS score 40', 'Complex, multi-morbid'),
  ('R29.741', 'Complex condition / Frail elderly', 'high', 'NIHSS score 41', 'Complex, multi-morbid'),
  ('R29.742', 'Complex condition / Frail elderly', 'high', 'NIHSS score 42', 'Complex, multi-morbid'),
  ('R29.810', 'Complex condition / Frail elderly', 'high', 'Facial weakness', 'Complex, multi-morbid'),
  ('R29.818', 'Complex condition / Frail elderly', 'high', 'Other symptoms and signs involving the nervous system', 'Complex, multi-morbid'),
  ('R29.890', 'Complex condition / Frail elderly', 'high', 'Loss of height', 'Complex, multi-morbid'),
  ('R29.891', 'Complex condition / Frail elderly', 'high', 'Ocular torticollis', 'Complex, multi-morbid'),
  ('R29.898', 'Complex condition / Frail elderly', 'high', 'Other symptoms and signs involving the musculoskeletal system', 'Complex, multi-morbid'),
  ('R29.90', 'Complex condition / Frail elderly', 'high', 'Unspecified symptoms and signs involving the nervous system', 'Complex, multi-morbid'),
  ('R29.91', 'Complex condition / Frail elderly', 'high', 'Unspecified symptoms and signs involving the musculoskeletal system', 'Complex, multi-morbid'),
  ('R30.0', 'Complex condition / Frail elderly', 'high', 'Dysuria', 'Complex, multi-morbid'),
  ('R30.1', 'Complex condition / Frail elderly', 'high', 'Vesical tenesmus', 'Complex, multi-morbid'),
  ('R30.9', 'Complex condition / Frail elderly', 'high', 'Painful micturition, unspecified', 'Complex, multi-morbid'),
  ('R31.0', 'Complex condition / Frail elderly', 'high', 'Gross hematuria', 'Complex, multi-morbid'),
  ('R31.1', 'Complex condition / Frail elderly', 'high', 'Benign essential microscopic hematuria', 'Complex, multi-morbid'),
  ('R31.21', 'Complex condition / Frail elderly', 'high', 'Asymptomatic microscopic hematuria', 'Complex, multi-morbid'),
  ('R31.29', 'Complex condition / Frail elderly', 'high', 'Other microscopic hematuria', 'Complex, multi-morbid'),
  ('R31.9', 'Complex condition / Frail elderly', 'high', 'Hematuria, unspecified', 'Complex, multi-morbid'),
  ('R32', 'Complex condition / Frail elderly', 'high', 'Unspecified urinary incontinence', 'Complex, multi-morbid'),
  ('R33.0', 'Complex condition / Frail elderly', 'high', 'Drug induced retention of urine', 'Complex, multi-morbid'),
  ('R33.8', 'Complex condition / Frail elderly', 'high', 'Other retention of urine', 'Complex, multi-morbid'),
  ('R33.9', 'Complex condition / Frail elderly', 'high', 'Retention of urine, unspecified', 'Complex, multi-morbid'),
  ('R34', 'Complex condition / Frail elderly', 'high', 'Anuria and oliguria', 'Complex, multi-morbid'),
  ('R35.0', 'Complex condition / Frail elderly', 'high', 'Frequency of micturition', 'Complex, multi-morbid'),
  ('R35.1', 'Complex condition / Frail elderly', 'high', 'Nocturia', 'Complex, multi-morbid'),
  ('R35.8', 'Complex condition / Frail elderly', 'high', 'Other polyuria', 'Complex, multi-morbid'),
  ('R36.0', 'Complex condition / Frail elderly', 'high', 'Urethral discharge without blood', 'Complex, multi-morbid'),
  ('R36.1', 'Complex condition / Frail elderly', 'high', 'Hematospermia', 'Complex, multi-morbid'),
  ('R36.9', 'Complex condition / Frail elderly', 'high', 'Urethral discharge, unspecified', 'Complex, multi-morbid'),
  ('R37', 'Complex condition / Frail elderly', 'high', 'Sexual dysfunction, unspecified', 'Complex, multi-morbid'),
  ('R39.0', 'Complex condition / Frail elderly', 'high', 'Extravasation of urine', 'Complex, multi-morbid'),
  ('R39.11', 'Complex condition / Frail elderly', 'high', 'Hesitancy of micturition', 'Complex, multi-morbid'),
  ('R39.12', 'Complex condition / Frail elderly', 'high', 'Poor urinary stream', 'Complex, multi-morbid'),
  ('R39.13', 'Complex condition / Frail elderly', 'high', 'Splitting of urinary stream', 'Complex, multi-morbid'),
  ('R39.14', 'Complex condition / Frail elderly', 'high', 'Feeling of incomplete bladder emptying', 'Complex, multi-morbid'),
  ('R39.15', 'Complex condition / Frail elderly', 'high', 'Urgency of urination', 'Complex, multi-morbid'),
  ('R39.16', 'Complex condition / Frail elderly', 'high', 'Straining to void', 'Complex, multi-morbid'),
  ('R39.191', 'Complex condition / Frail elderly', 'high', 'Need to immediately re-void', 'Complex, multi-morbid'),
  ('R39.192', 'Complex condition / Frail elderly', 'high', 'Position dependent micturition', 'Complex, multi-morbid'),
  ('R39.198', 'Complex condition / Frail elderly', 'high', 'Other difficulties with micturition', 'Complex, multi-morbid'),
  ('R39.2', 'Complex condition / Frail elderly', 'high', 'Extrarenal uremia', 'Complex, multi-morbid'),
  ('R39.81', 'Complex condition / Frail elderly', 'high', 'Functional urinary incontinence', 'Complex, multi-morbid'),
  ('R39.82', 'Complex condition / Frail elderly', 'high', 'Chronic bladder pain', 'Complex, multi-morbid'),
  ('R39.89', 'Complex condition / Frail elderly', 'high', 'Other symptoms and signs involving the genitourinary system', 'Complex, multi-morbid'),
  ('R39.9', 'Complex condition / Frail elderly', 'high', 'Unspecified symptoms and signs involving the genitourinary system', 'Complex, multi-morbid'),
  ('R40.0', 'Complex condition / Frail elderly', 'high', 'Somnolence', 'Complex, multi-morbid'),
  ('R40.1', 'Complex condition / Frail elderly', 'high', 'Stupor', 'Complex, multi-morbid'),
  ('R40.20', 'Complex condition / Frail elderly', 'high', 'Unspecified coma', 'Complex, multi-morbid'),
  ('R40.2110', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, never, unspecified time', 'Complex, multi-morbid'),
  ('R40.2111', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, never, in the field', 'Complex, multi-morbid'),
  ('R40.2112', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, never, at arrival to emergency department', 'Complex, multi-morbid'),
  ('R40.2113', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, never, at hospital admission', 'Complex, multi-morbid'),
  ('R40.2114', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, never, 24 hours or more after hospital admission', 'Complex, multi-morbid'),
  ('R40.2120', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to pain, unspecified time', 'Complex, multi-morbid'),
  ('R40.2121', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to pain, in the field', 'Complex, multi-morbid'),
  ('R40.2122', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to pain, at arrival to emergency department', 'Complex, multi-morbid'),
  ('R40.2123', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to pain, at hospital admission', 'Complex, multi-morbid'),
  ('R40.2124 ', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to pain, 24 hours or more after hospital admission', 'Complex, multi-morbid'),
  ('R40.2130', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to sound, unspecified time', 'Complex, multi-morbid'),
  ('R40.2131', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to sound, in the field', 'Complex, multi-morbid'),
  ('R40.2132', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to sound, at arrival to emergency department', 'Complex, multi-morbid'),
  ('R40.2133', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to sound, at hospital admission', 'Complex, multi-morbid'),
  ('R40.2134', 'Complex condition / Frail elderly', 'high', 'Coma scale, eyes open, to sound, 24 hours or more after hospital admission', 'Complex, multi-morbid');

-- Add corresponding entries to home_codes if they don't exist
INSERT INTO home_codes ("Care Setting", "Systems of Care", "ICD FamilyCode")
SELECT 
    'HOME',
    systems_of_care,
    icd_code
FROM home_services_mapping
WHERE NOT EXISTS (
    SELECT 1 FROM home_codes WHERE "ICD FamilyCode" = home_services_mapping.icd_code
)
ON CONFLICT DO NOTHING;