INSERT INTO home_services_mapping 
(icd_code, service, confidence, mapping_logic, systems_of_care) 
VALUES
  -- Routine health checks (100 codes)
  ('Z03.810', 'Routine health checks', 'high', 'Encounter for observation for suspected exposure to anthrax', 'Wellness and longevity'),
  ('Z03.811', 'Routine health checks', 'high', 'Encounter for observation for suspected exposure to biological agents', 'Wellness and longevity'),
  ('Z03.812', 'Routine health checks', 'high', 'Encounter for observation for suspected exposure to chemical agents', 'Wellness and longevity'),
  ('Z03.818', 'Routine health checks', 'high', 'Encounter for observation for suspected exposure to other agents', 'Wellness and longevity'),
  ('Z03.89', 'Routine health checks', 'high', 'Encounter for observation for other suspected diseases and conditions ruled out', 'Wellness and longevity'),
  ('Z04.1', 'Routine health checks', 'high', 'Encounter for examination and observation following transport accident', 'Wellness and longevity'),
  ('Z04.2', 'Routine health checks', 'high', 'Encounter for examination and observation following work accident', 'Wellness and longevity'),
  ('Z04.3', 'Routine health checks', 'high', 'Encounter for examination and observation following other accident', 'Wellness and longevity'),
  ('Z04.41', 'Routine health checks', 'high', 'Encounter for examination and observation following alleged adult rape', 'Wellness and longevity'),
  ('Z04.42', 'Routine health checks', 'high', 'Encounter for examination and observation following alleged child rape', 'Wellness and longevity'),
  ('Z04.6', 'Routine health checks', 'high', 'Encounter for general psychiatric examination, requested by authority', 'Wellness and longevity'),
  ('Z04.71', 'Routine health checks', 'high', 'Encounter for examination and observation following alleged adult physical abuse', 'Wellness and longevity'),
  ('Z04.72', 'Routine health checks', 'high', 'Encounter for examination and observation following alleged child physical abuse', 'Wellness and longevity'),
  ('Z04.81', 'Routine health checks', 'high', 'Encounter for examination and observation of victim following forced sexual exploitation', 'Wellness and longevity'),
  ('Z04.82', 'Routine health checks', 'high', 'Encounter for examination and observation of victim following forced labor exploitation', 'Wellness and longevity'),
  ('Z04.89', 'Routine health checks', 'high', 'Encounter for examination and observation for other specified reasons', 'Wellness and longevity'),
  ('Z04.9', 'Routine health checks', 'high', 'Encounter for examination and observation for unspecified reason', 'Wellness and longevity'),
  ('Z08', 'Routine health checks', 'high', 'Encounter for follow-up examination after completed treatment for malignant neoplasm', 'Wellness and longevity'),
  ('Z09', 'Routine health checks', 'high', 'Encounter for follow-up examination after completed treatment for conditions other than malignant neoplasm', 'Wellness and longevity'),
  ('Z11.0', 'Routine health checks', 'high', 'Encounter for screening for intestinal infectious diseases', 'Wellness and longevity'),
  ('Z11.1', 'Routine health checks', 'high', 'Encounter for screening for respiratory tuberculosis', 'Wellness and longevity'),
  ('Z11.2', 'Routine health checks', 'high', 'Encounter for screening for other bacterial diseases', 'Wellness and longevity'),
  ('Z11.3', 'Routine health checks', 'high', 'Encounter for screening for infections with a predominantly sexual mode of transmission', 'Wellness and longevity'),
  ('Z11.4', 'Routine health checks', 'high', 'Encounter for screening for human immunodeficiency virus [HIV]', 'Wellness and longevity'),
  ('Z11.51', 'Routine health checks', 'high', 'Encounter for screening for human papillomavirus (HPV)', 'Wellness and longevity'),
  ('Z11.59', 'Routine health checks', 'high', 'Encounter for screening for other viral diseases', 'Wellness and longevity'),
  ('Z11.6', 'Routine health checks', 'high', 'Encounter for screening for other protozoal diseases and helminthiases', 'Wellness and longevity'),
  ('Z11.8', 'Routine health checks', 'high', 'Encounter for screening for other infectious and parasitic diseases', 'Wellness and longevity'),
  ('Z11.9', 'Routine health checks', 'high', 'Encounter for screening for infectious and parasitic diseases, unspecified', 'Wellness and longevity'),
  ('Z12.0', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of stomach', 'Wellness and longevity'),
  ('Z12.10', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of intestinal tract, unspecified', 'Wellness and longevity'),
  ('Z12.11', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of colon', 'Wellness and longevity'),
  ('Z12.12', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of rectum', 'Wellness and longevity'),
  ('Z12.13', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of small intestine', 'Wellness and longevity'),
  ('Z12.2', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of respiratory organs', 'Wellness and longevity'),
  ('Z12.31', 'Routine health checks', 'high', 'Encounter for screening mammogram for malignant neoplasm of breast', 'Wellness and longevity'),
  ('Z12.39', 'Routine health checks', 'high', 'Encounter for other screening for malignant neoplasm of breast', 'Wellness and longevity'),
  ('Z12.4', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of cervix', 'Wellness and longevity'),
  ('Z12.5', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of prostate', 'Wellness and longevity'),
  ('Z12.6', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of bladder', 'Wellness and longevity'),
  ('Z12.71', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of testis', 'Wellness and longevity'),
  ('Z12.72', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of vagina', 'Wellness and longevity'),
  ('Z12.73', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of ovary', 'Wellness and longevity'),
  ('Z12.79', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of other genitourinary organs', 'Wellness and longevity'),
  ('Z12.81', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of oral cavity', 'Wellness and longevity'),
  ('Z12.82', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of nervous system', 'Wellness and longevity'),
  ('Z12.83', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of skin', 'Wellness and longevity'),
  ('Z12.89', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm of other sites', 'Wellness and longevity'),
  ('Z12.9', 'Routine health checks', 'high', 'Encounter for screening for malignant neoplasm, site unspecified', 'Wellness and longevity'),
  ('Z13.0', 'Routine health checks', 'high', 'Encounter for screening for diseases of the blood and blood-forming organs', 'Wellness and longevity'),
  ('Z13.1', 'Routine health checks', 'high', 'Encounter for screening for diabetes mellitus', 'Wellness and longevity'),
  ('Z13.21', 'Routine health checks', 'high', 'Encounter for screening for nutritional disorder', 'Wellness and longevity'),
  ('Z13.220', 'Routine health checks', 'high', 'Encounter for screening for lipoid disorders', 'Wellness and longevity'),
  ('Z13.228', 'Routine health checks', 'high', 'Encounter for screening for other metabolic disorders', 'Wellness and longevity'),
  ('Z13.29', 'Routine health checks', 'high', 'Encounter for screening for other suspected endocrine disorder', 'Wellness and longevity'),
  ('Z13.30', 'Routine health checks', 'high', 'Encounter for screening examination for mental health and behavioral disorders, unspecified', 'Wellness and longevity'),
  ('Z13.31', 'Routine health checks', 'high', 'Encounter for screening for depression', 'Wellness and longevity'),
  ('Z13.32', 'Routine health checks', 'high', 'Encounter for screening for maternal depression', 'Wellness and longevity'),
  ('Z13.39', 'Routine health checks', 'high', 'Encounter for screening examination for other mental health and behavioral disorders', 'Wellness and longevity'),
  ('Z13.40', 'Routine health checks', 'high', 'Encounter for screening for unspecified developmental delays', 'Wellness and longevity'),
  ('Z13.41', 'Routine health checks', 'high', 'Encounter for autism screening', 'Wellness and longevity'),
  ('Z13.42', 'Routine health checks', 'high', 'Encounter for screening for global developmental delays', 'Wellness and longevity'),
  ('Z13.49', 'Routine health checks', 'high', 'Encounter for screening for other developmental delays', 'Wellness and longevity'),
  ('Z13.5', 'Routine health checks', 'high', 'Encounter for screening for eye and ear disorders', 'Wellness and longevity'),
  ('Z13.6', 'Routine health checks', 'high', 'Encounter for screening for cardiovascular disorders', 'Wellness and longevity'),
  ('Z13.71', 'Routine health checks', 'high', 'Encounter for nonprocreative screening for genetic disease carrier status', 'Wellness and longevity'),
  ('Z13.79', 'Routine health checks', 'high', 'Encounter for other screening for genetic and chromosomal anomalies', 'Wellness and longevity'),
  ('Z13.810', 'Routine health checks', 'high', 'Encounter for screening for upper gastrointestinal disorder', 'Wellness and longevity'),
  ('Z13.811', 'Routine health checks', 'high', 'Encounter for screening for lower gastrointestinal disorder', 'Wellness and longevity'),
  ('Z13.818', 'Routine health checks', 'high', 'Encounter for screening for other digestive system disorders', 'Wellness and longevity'),
  ('Z13.820', 'Routine health checks', 'high', 'Encounter for screening for osteoporosis', 'Wellness and longevity'),
  ('Z13.828', 'Routine health checks', 'high', 'Encounter for screening for other musculoskeletal disorder', 'Wellness and longevity'),
  ('Z13.83', 'Routine health checks', 'high', 'Encounter for screening for respiratory disorder NEC', 'Wellness and longevity'),
  ('Z13.84', 'Routine health checks', 'high', 'Encounter for screening for dental disorders', 'Wellness and longevity'),
  ('Z13.850', 'Routine health checks', 'high', 'Encounter for screening for traumatic brain injury', 'Wellness and longevity'),
  ('Z13.858', 'Routine health checks', 'high', 'Encounter for screening for other nervous system disorders', 'Wellness and longevity'),
  ('Z13.88', 'Routine health checks', 'high', 'Encounter for screening for disorder due to exposure to contaminants', 'Wellness and longevity'),
  ('Z13.89', 'Routine health checks', 'high', 'Encounter for screening for other disorder', 'Wellness and longevity'),
  ('Z13.9', 'Routine health checks', 'high', 'Encounter for screening, unspecified', 'Wellness and longevity'),
  ('Z14.01', 'Routine health checks', 'high', 'Asymptomatic hemophilia A carrier', 'Wellness and longevity'),
  ('Z14.02', 'Routine health checks', 'high', 'Symptomatic hemophilia A carrier', 'Wellness and longevity'),
  ('Z14.1', 'Routine health checks', 'high', 'Cystic fibrosis carrier', 'Wellness and longevity'),
  ('Z14.8', 'Routine health checks', 'high', 'Genetic carrier of other disease', 'Wellness and longevity'),
  ('Z15.01', 'Routine health checks', 'high', 'Genetic susceptibility to malignant neoplasm of breast', 'Wellness and longevity'),
  ('Z15.02', 'Routine health checks', 'high', 'Genetic susceptibility to malignant neoplasm of ovary', 'Wellness and longevity'),
  ('Z15.03', 'Routine health checks', 'high', 'Genetic susceptibility to malignant neoplasm of prostate', 'Wellness and longevity'),
  ('Z15.04', 'Routine health checks', 'high', 'Genetic susceptibility to malignant neoplasm of endometrium', 'Wellness and longevity'),
  ('Z15.09', 'Routine health checks', 'high', 'Genetic susceptibility to other malignant neoplasm', 'Wellness and longevity'),
  ('Z15.81', 'Routine health checks', 'high', 'Genetic susceptibility to multiple endocrine neoplasia [MEN]', 'Wellness and longevity'),
  ('Z15.89', 'Routine health checks', 'high', 'Genetic susceptibility to other disease', 'Wellness and longevity'),
  ('Z16.11', 'Routine health checks', 'high', 'Resistance to penicillins', 'Wellness and longevity'),
  ('Z16.12', 'Routine health checks', 'high', 'Resistance to extended spectrum beta lactamase (ESBL)', 'Wellness and longevity'),
  ('Z16.19', 'Routine health checks', 'high', 'Resistance to other specified beta lactam antibiotics', 'Wellness and longevity'),
  ('Z16.20', 'Routine health checks', 'high', 'Resistance to unspecified antibiotic', 'Wellness and longevity'),
  ('Z16.21', 'Routine health checks', 'high', 'Resistance to vancomycin', 'Wellness and longevity'),
  ('Z16.22', 'Routine health checks', 'high', 'Resistance to vancomycin related antibiotics', 'Wellness and longevity'),
  ('Z16.23', 'Routine health checks', 'high', 'Resistance to quinolones and fluoroquinolones', 'Wellness and longevity'),
  ('Z16.24', 'Routine health checks', 'high', 'Resistance to multiple antibiotics', 'Wellness and longevity'),
  ('Z16.29', 'Routine health checks', 'high', 'Resistance to other single specified antibiotic', 'Wellness and longevity'),
  ('Z16.30', 'Routine health checks', 'high', 'Resistance to unspecified antimicrobial drugs', 'Wellness and longevity'),
  ('Z16.31', 'Routine health checks', 'high', 'Resistance to antiparasitic drug(s)', 'Wellness and longevity'),
  ('Z16.32', 'Routine health checks', 'high', 'Resistance to antifungal drug(s)', 'Wellness and longevity'),
  ('Z16.33', 'Routine health checks', 'high', 'Resistance to antiviral drug(s)', 'Wellness and longevity'),
  ('Z16.341', 'Routine health checks', 'high', 'Resistance to single antimycobacterial drug', 'Wellness and longevity'),
  ('Z16.342', 'Routine health checks', 'high', 'Resistance to multiple antimycobacterial drugs', 'Wellness and longevity'),
  ('Z16.35', 'Routine health checks', 'high', 'Resistance to multiple antimicrobial drugs', 'Wellness and longevity'),
  ('Z16.39', 'Routine health checks', 'high', 'Resistance to other specified antimicrobial drug', 'Wellness and longevity'),
  ('Z17.0', 'Routine health checks', 'high', 'Estrogen receptor positive status [ER+]', 'Wellness and longevity'),
  ('Z17.1', 'Routine health checks', 'high', 'Estrogen receptor negative status [ER-]', 'Wellness and longevity'),
  ('Z18.01', 'Routine health checks', 'high', 'Retained depleted uranium fragments', 'Wellness and longevity'),
  ('Z18.09', 'Routine health checks', 'high', 'Other retained radioactive fragments', 'Wellness and longevity'),
  ('Z18.10', 'Routine health checks', 'high', 'Retained metal fragments, unspecified', 'Wellness and longevity'),
  ('Z18.11', 'Routine health checks', 'high', 'Retained magnetic metal fragments', 'Wellness and longevity'),
  ('Z18.12', 'Routine health checks', 'high', 'Retained nonmagnetic metal fragments', 'Wellness and longevity'),
  ('Z18.2', 'Routine health checks', 'high', 'Retained plastic fragments', 'Wellness and longevity'),
  ('Z18.31', 'Routine health checks', 'high', 'Retained animal quills or spines', 'Wellness and longevity'),
  ('Z18.32', 'Routine health checks', 'high', 'Retained tooth', 'Wellness and longevity'),
  ('Z18.33', 'Routine health checks', 'high', 'Retained wood fragments', 'Wellness and longevity'),
  ('Z18.39', 'Routine health checks', 'high', 'Other retained organic fragments', 'Wellness and longevity'),
  ('Z18.81', 'Routine health checks', 'high', 'Retained glass fragments', 'Wellness and longevity'),
  ('Z18.83', 'Routine health checks', 'high', 'Retained stone or crystalline fragments', 'Wellness and longevity'),
  ('Z18.89', 'Routine health checks', 'high', 'Other specified retained foreign body fragments', 'Wellness and longevity'),
  ('Z18.9', 'Routine health checks', 'high', 'Retained foreign body fragments, unspecified material', 'Wellness and longevity'),

  -- Chronic metabolic diseases (100 codes)
  ('E50.0', 'Chronic metabolic diseases', 'high', 'Vitamin A deficiency with conjunctival xerosis', 'Chronic conditions'),
  ('E50.1', 'Chronic metabolic diseases', 'high', 'Vitamin A deficiency with Bitots spot and conjunctival xerosis', 'Chronic conditions'),
  ('E50.2', 'Chronic metabolic diseases', 'high', 'Vitamin A deficiency with corneal xerosis', 'Chronic conditions'),
  ('E50.3', 'Chronic metabolic diseases', 'high', 'Vitamin A deficiency with corneal ulceration and xerosis', 'Chronic conditions'),
  ('E50.4', 'Chronic metabolic diseases', 'high', 'Vitamin A deficiency with keratomalacia', 'Chronic conditions'),
  ('E50.5', 'Chronic metabolic diseases', 'high', 'Vitamin A deficiency with night blindness', 'Chronic conditions'),
  ('E50.6', 'Chronic metabolic diseases', 'high', 'Vitamin A deficiency with xerophthalmic scars of cornea', 'Chronic conditions'),
  ('E50.7', 'Chronic metabolic diseases', 'high', 'Other ocular manifestations of vitamin A deficiency', 'Chronic conditions'),
  ('E50.8', 'Chronic metabolic diseases', 'high', 'Other manifestations of vitamin A deficiency', 'Chronic conditions'),
  ('E50.9', 'Chronic metabolic diseases', 'high', 'Vitamin A deficiency, unspecified', 'Chronic conditions'),
  ('E51.11', 'Chronic metabolic diseases', 'high', 'Dry beriberi', 'Chronic conditions'),
  ('E51.12', 'Chronic metabolic diseases', 'high', 'Wet beriberi', 'Chronic conditions'),
  ('E51.2', 'Chronic metabolic diseases', 'high', 'Wernicke encephalopathy', 'Chronic conditions'),
  ('E51.8', 'Chronic metabolic diseases', 'high', 'Other manifestations of thiamine deficiency', 'Chronic conditions'),
  ('E51.9', 'Chronic metabolic diseases', 'high', 'Thiamine deficiency, unspecified', 'Chronic conditions'),
  ('E52', 'Chronic metabolic diseases', 'high', 'Niacin deficiency [pellagra]', 'Chronic conditions'),
  ('E53.0', 'Chronic metabolic diseases', 'high', 'Riboflavin deficiency', 'Chronic conditions'),
  ('E53.1', 'Chronic metabolic diseases', 'high', 'Pyridoxine deficiency', 'Chronic conditions'),
  ('E53.8', 'Chronic metabolic diseases', 'high', 'Deficiency of other specified B group vitamins', 'Chronic conditions'),
  ('E53.9', 'Chronic metabolic diseases', 'high', 'Vitamin B deficiency, unspecified', 'Chronic conditions'),
  ('E54', 'Chronic metabolic diseases', 'high', 'Ascorbic acid deficiency', 'Chronic conditions'),
  ('E55.0', 'Chronic metabolic diseases', 'high', 'Rickets, active', 'Chronic conditions'),
  ('E55.9', 'Chronic metabolic diseases', 'high', 'Vitamin D deficiency, unspecified', 'Chronic conditions'),
  ('E56.0', 'Chronic metabolic diseases', 'high', 'Deficiency of vitamin E', 'Chronic conditions'),
  ('E56.1', 'Chronic metabolic diseases', 'high', 'Deficiency of vitamin K', 'Chronic conditions'),
  ('E56.8', 'Chronic metabolic diseases', 'high', 'Deficiency of other vitamins', 'Chronic conditions'),
  ('E56.9', 'Chronic metabolic diseases', 'high', 'Vitamin deficiency, unspecified', 'Chronic conditions'),
  ('E58', 'Chronic metabolic diseases', 'high', 'Dietary calcium deficiency', 'Chronic conditions'),
  ('E59', 'Chronic metabolic diseases', 'high', 'Dietary selenium deficiency', 'Chronic conditions'),
  ('E60', 'Chronic metabolic diseases', 'high', 'Dietary zinc deficiency', 'Chronic conditions'),
  ('E61.0', 'Chronic metabolic diseases', 'high', 'Copper deficiency', 'Chronic conditions'),
  ('E61.1', 'Chronic metabolic diseases', 'high', 'Iron deficiency', 'Chronic conditions'),
  ('E61.2', 'Chronic metabolic diseases', 'high', 'Magnesium deficiency', 'Chronic conditions'),
  ('E61.3', 'Chronic metabolic diseases', 'high', 'Manganese deficiency', 'Chronic conditions'),
  ('E61.4', 'Chronic metabolic diseases', 'high', 'Chromium deficiency', 'Chronic conditions'),
  ('E61.5', 'Chronic metabolic diseases', 'high', 'Molybdenum deficiency', 'Chronic conditions'),
  ('E61.6', 'Chronic metabolic diseases', 'high', 'Vanadium deficiency', 'Chronic conditions'),
  ('E61.7', 'Chronic metabolic diseases', 'high', 'Deficiency of multiple nutrient elements', 'Chronic conditions'),
  ('E61.8', 'Chronic metabolic diseases', 'high', 'Deficiency of other specified nutrient elements', 'Chronic conditions'),
  ('E61.9', 'Chronic metabolic diseases', 'high', 'Deficiency of nutrient element, unspecified', 'Chronic conditions'),
  ('E63.0', 'Chronic metabolic diseases', 'high', 'Essential fatty acid [EFA] deficiency', 'Chronic conditions'),
  ('E63.1', 'Chronic metabolic diseases', 'high', 'Imbalance of constituents of food intake', 'Chronic conditions'),
  ('E63.8', 'Chronic metabolic diseases', 'high', 'Other specified nutritional deficiencies', 'Chronic conditions'),
  ('E63.9', 'Chronic metabolic diseases', 'high', 'Nutritional deficiency, unspecified', 'Chronic conditions'),
  ('E64.0', 'Chronic metabolic diseases', 'high', 'Sequelae of protein-calorie malnutrition', 'Chronic conditions'),
  ('E64.1', 'Chronic metabolic diseases', 'high', 'Sequelae of vitamin A deficiency', 'Chronic conditions'),
  ('E64.2', 'Chronic metabolic diseases', 'high', 'Sequelae of vitamin C deficiency', 'Chronic conditions'),
  ('E64.3', 'Chronic metabolic diseases', 'high', 'Sequelae of rickets', 'Chronic conditions'),
  ('E64.8', 'Chronic metabolic diseases', 'high', 'Sequelae of other nutritional deficiencies', 'Chronic conditions'),
  ('E64.9', 'Chronic metabolic diseases', 'high', 'Sequelae of unspecified nutritional deficiency', 'Chronic conditions'),
  ('E65', 'Chronic metabolic diseases', 'high', 'Localized adiposity', 'Chronic conditions'),
  ('E66.01', 'Chronic metabolic diseases', 'high', 'Morbid (severe) obesity due to excess calories', 'Chronic conditions'),
  ('E66.09', 'Chronic metabolic diseases', 'high', 'Other obesity due to excess calories', 'Chronic conditions'),
  ('E66.1', 'Chronic metabolic diseases', 'high', 'Drug-induced obesity', 'Chronic conditions'),
  ('E66.2', 'Chronic metabolic diseases', 'high', 'Morbid (severe) obesity with alveolar hypoventilation', 'Chronic conditions'),
  ('E66.3', 'Chronic metabolic diseases', 'high', 'Overweight', 'Chronic conditions'),
  ('E66.8', 'Chronic metabolic diseases', 'high', 'Other obesity', 'Chronic conditions'),
  ('E66.9', 'Chronic metabolic diseases', 'high', 'Obesity, unspecified', 'Chronic conditions'),
  ('E67.0', 'Chronic metabolic diseases', 'high', 'Hypervitaminosis A', 'Chronic conditions'),
  ('E67.1', 'Chronic metabolic diseases', 'high', 'Hypercarotenemia', 'Chronic conditions'),
  ('E67.2', 'Chronic metabolic diseases', 'high', 'Megavitamin-B6 syndrome', 'Chronic conditions'),
  ('E67.3', 'Chronic metabolic diseases', 'high', 'Hypervitaminosis D', 'Chronic conditions'),
  ('E67.8', 'Chronic metabolic diseases', 'high', 'Other specified hyperalimentation', 'Chronic conditions'),
  ('E68', 'Chronic metabolic diseases', 'high', 'Sequelae of hyperalimentation', 'Chronic conditions'),
  ('E70.0', 'Chronic metabolic diseases', 'high', 'Classical phenylketonuria', 'Chronic conditions'),
  ('E70.1', 'Chronic metabolic diseases', 'high', 'Other hyperphenylalaninemias', 'Chronic conditions'),
  ('E70.20', 'Chronic metabolic diseases', 'high', 'Disorder of tyrosine metabolism, unspecified', 'Chronic conditions'),
  ('E70.21', 'Chronic metabolic diseases', 'high', 'Tyrosinemia', 'Chronic conditions'),
  ('E70.29', 'Chronic metabolic diseases', 'high', 'Other disorders of tyrosine metabolism', 'Chronic conditions'),
  ('E70.30', 'Chronic metabolic diseases', 'high', 'Albinism, unspecified', 'Chronic conditions'),
  ('E70.310', 'Chronic metabolic diseases', 'high', 'X-linked ocular albinism', 'Chronic conditions'),
  ('E70.311', 'Chronic metabolic diseases', 'high', 'Autosomal recessive ocular albinism', 'Chronic conditions'),
  ('E70.318', 'Chronic metabolic diseases', 'high', 'Other ocular albinism', 'Chronic conditions'),
  ('E70.319', 'Chronic metabolic diseases', 'high', 'Ocular albinism, unspecified', 'Chronic conditions'),
  ('E70.320', 'Chronic metabolic diseases', 'high', 'Tyrosinase negative oculocutaneous albinism', 'Chronic conditions'),
  ('E70.321', 'Chronic metabolic diseases', 'high', 'Tyrosinase positive oculocutaneous albinism', 'Chronic conditions'),
  ('E70.328', 'Chronic metabolic diseases', 'high', 'Other oculocutaneous albinism', 'Chronic conditions'),
  ('E70.329', 'Chronic metabolic diseases', 'high', 'Oculocutaneous albinism, unspecified', 'Chronic conditions'),
  ('E70.330', 'Chronic metabolic diseases', 'high', 'Chediak-Higashi syndrome', 'Chronic conditions'),
  ('E70.331', 'Chronic metabol ic diseases', 'high', 'Hermansky-Pudlak syndrome', 'Chronic conditions'),
  ('E70.338', 'Chronic metabolic diseases', 'high', 'Other albinism with hematologic abnormality', 'Chronic conditions'),
  ('E70.339', 'Chronic metabolic diseases', 'high', 'Albinism with hematologic abnormality, unspecified', 'Chronic conditions'),
  ('E70.39', 'Chronic metabolic diseases', 'high', 'Other specified albinism', 'Chronic conditions'),
  ('E70.40', 'Chronic metabolic diseases', 'high', 'Disorders of histidine metabolism, unspecified', 'Chronic conditions'),
  ('E70.41', 'Chronic metabolic diseases', 'high', 'Histidinemia', 'Chronic conditions'),
  ('E70.49', 'Chronic metabolic diseases', 'high', 'Other disorders of histidine metabolism', 'Chronic conditions'),
  ('E70.5', 'Chronic metabolic diseases', 'high', 'Disorders of tryptophan metabolism', 'Chronic conditions'),
  ('E70.8', 'Chronic metabolic diseases', 'high', 'Other disorders of aromatic amino-acid metabolism', 'Chronic conditions'),
  ('E70.9', 'Chronic metabolic diseases', 'high', 'Disorder of aromatic amino-acid metabolism, unspecified', 'Chronic conditions'),
  ('E71.0', 'Chronic metabolic diseases', 'high', 'Maple-syrup-urine disease', 'Chronic conditions'),
  ('E71.110', 'Chronic metabolic diseases', 'high', 'Isovaleric acidemia', 'Chronic conditions'),
  ('E71.111', 'Chronic metabolic diseases', 'high', 'Methylmalonic acidemia', 'Chronic conditions'),
  ('E71.118', 'Chronic metabolic diseases', 'high', 'Other branched-chain organic acidurias', 'Chronic conditions'),
  ('E71.120', 'Chronic metabolic diseases', 'high', 'Propionic acidemia', 'Chronic conditions'),
  ('E71.121', 'Chronic metabolic diseases', 'high', 'Methylmalonyl-CoA mutase deficiency', 'Chronic conditions'),
  ('E71.128', 'Chronic metabolic diseases', 'high', 'Other disorders of propionate metabolism', 'Chronic conditions'),
  ('E71.19', 'Chronic metabolic diseases', 'high', 'Other disorders of branched-chain amino-acid metabolism', 'Chronic conditions'),
  ('E71.2', 'Chronic metabolic diseases', 'high', 'Disorder of branched-chain amino-acid metabolism, unspecified', 'Chronic conditions'),
  ('E71.30', 'Chronic metabolic diseases', 'high', 'Disorder of fatty-acid metabolism, unspecified', 'Chronic conditions'),
  ('E71.310', 'Chronic metabolic diseases', 'high', 'Long chain/very long chain acyl CoA dehydrogenase deficiency', 'Chronic conditions'),
  ('E71.311', 'Chronic metabolic diseases', 'high', 'Medium chain acyl CoA dehydrogenase deficiency', 'Chronic conditions'),
  ('E71.312', 'Chronic metabolic diseases', 'high', 'Short chain acyl CoA dehydrogenase deficiency', 'Chronic conditions'),
  ('E71.313', 'Chronic metabolic diseases', 'high', 'Glutaric aciduria type II', 'Chronic conditions'),
  ('E71.314', 'Chronic metabolic diseases', 'high', 'Muscle carnitine palmitoyltransferase deficiency', 'Chronic conditions'),
  ('E71.318', 'Chronic metabolic diseases', 'high', 'Other disorders of fatty-acid oxidation', 'Chronic conditions'),
  ('E71.32', 'Chronic metabolic diseases', 'high', 'Disorders of ketone metabolism', 'Chronic conditions'),
  ('E71.39', 'Chronic metabolic diseases', 'high', 'Other disorders of fatty-acid metabolism', 'Chronic conditions'),
  ('E71.40', 'Chronic metabolic diseases', 'high', 'Disorder of carnitine metabolism, unspecified', 'Chronic conditions'),
  ('E71.41', 'Chronic metabolic diseases', 'high', 'Primary carnitine deficiency', 'Chronic conditions'),
  ('E71.42', 'Chronic metabolic diseases', 'high', 'Carnitine deficiency due to inborn errors of metabolism', 'Chronic conditions'),
  ('E71.43', 'Chronic metabolic diseases', 'high', 'Iatrogenic carnitine deficiency', 'Chronic conditions'),
  ('E71.440', 'Chronic metabolic diseases', 'high', 'Ruvalcaba-Myhre-Smith syndrome', 'Chronic conditions'),
  ('E71.448', 'Chronic metabolic diseases', 'high', 'Other secondary carnitine deficiency', 'Chronic conditions'),
  ('E71.50', 'Chronic metabolic diseases', 'high', 'Peroxisomal disorder, unspecified', 'Chronic conditions'),
  ('E71.510', 'Chronic metabolic diseases', 'high', 'Zellweger syndrome', 'Chronic conditions'),
  ('E71.511', 'Chronic metabolic diseases', 'high', 'Neonatal adrenoleukodystrophy', 'Chronic conditions'),
  ('E71.518', 'Chronic metabolic diseases', 'high', 'Other disorders of peroxisome biogenesis', 'Chronic conditions'),
  ('E71.520', 'Chronic metabolic diseases', 'high', 'Childhood cerebral X-linked adrenoleukodystrophy', 'Chronic conditions'),
  ('E71.521', 'Chronic metabolic diseases', 'high', 'Adolescent X-linked adrenoleukodystrophy', 'Chronic conditions'),
  ('E71.522', 'Chronic metabolic diseases', 'high', 'Adrenomyeloneuropathy', 'Chronic conditions'),
  ('E71.528', 'Chronic metabolic diseases', 'high', 'Other X-linked adrenoleukodystrophy', 'Chronic conditions'),
  ('E71.529', 'Chronic metabolic diseases', 'high', 'X-linked adrenoleukodystrophy, unspecified type', 'Chronic conditions'),
  ('E71.53', 'Chronic metabolic diseases', 'high', 'Other group 2 peroxisomal disorders', 'Chronic conditions'),
  ('E71.540', 'Chronic metabolic diseases', 'high', 'Rhizomelic chondrodysplasia punctata', 'Chronic conditions'),
  ('E71.541', 'Chronic metabolic diseases', 'high', 'Zellweger-like syndrome', 'Chronic conditions'),
  ('E71.542', 'Chronic metabolic diseases', 'high', 'Other group 3 peroxisomal disorders', 'Chronic conditions'),
  ('E71.548', 'Chronic metabolic diseases', 'high', 'Other peroxisomal disorders', 'Chronic conditions');

-- Add corresponding entries to home_codes if they don't exist
INSERT INTO home_codes ("Care Setting", "Systems of Care", "ICD FamilyCode")
SELECT 
    'HOME',
    systems_of_care,
    icd_code
FROM home_services_mapping
WHERE NOT EXISTS (
    SELECT 1 FROM home_codes WHERE "ICD FamilyCode" = home_services_mapping.icd_code
)
ON CONFLICT DO NOTHING;