/*
  # Add 200 additional ICD code mappings for home services

  1. New Mappings
    - Add 200 new ICD code mappings across different service types
    - Focus on unmapped codes from home_codes table
    - Ensure coverage across all systems of care
    - Include mix of high, medium, and low confidence mappings
*/

INSERT INTO home_services_mapping 
(icd_code, service, confidence, mapping_logic, systems_of_care) 
VALUES
  -- Chronic metabolic diseases (40 codes)
  ('E11.21', 'Chronic metabolic diseases', 'high', 'Type 2 diabetes with diabetic nephropathy requires regular monitoring', 'Chronic conditions'),
  ('E11.311', 'Chronic metabolic diseases', 'high', 'Type 2 diabetes with unspecified diabetic retinopathy requires monitoring', 'Chronic conditions'),
  ('E11.40', 'Chronic metabolic diseases', 'high', 'Type 2 diabetes with diabetic neuropathy requires regular care', 'Chronic conditions'),
  ('E11.51', 'Chronic metabolic diseases', 'high', 'Type 2 diabetes with diabetic peripheral angiopathy requires monitoring', 'Chronic conditions'),
  ('E11.65', 'Chronic metabolic diseases', 'high', 'Type 2 diabetes with hyperglycemia requires regular monitoring', 'Chronic conditions'),
  ('E11.69', 'Chronic metabolic diseases', 'high', 'Type 2 diabetes with other specified complication needs monitoring', 'Chronic conditions'),
  ('E11.8', 'Chronic metabolic diseases', 'high', 'Type 2 diabetes with unspecified complications requires care', 'Chronic conditions'),
  ('E13.9', 'Chronic metabolic diseases', 'high', 'Other specified diabetes mellitus without complications', 'Chronic conditions'),
  ('E66.01', 'Chronic metabolic diseases', 'high', 'Morbid obesity due to excess calories requires management', 'Chronic conditions'),
  ('E66.3', 'Chronic metabolic diseases', 'high', 'Overweight requires ongoing monitoring and management', 'Chronic conditions'),
  ('E78.1', 'Chronic metabolic diseases', 'high', 'Pure hyperglyceridemia requires regular monitoring', 'Chronic conditions'),
  ('E78.2', 'Chronic metabolic diseases', 'high', 'Mixed hyperlipidemia requires ongoing management', 'Chronic conditions'),
  ('E78.4', 'Chronic metabolic diseases', 'high', 'Other hyperlipidemia requires regular monitoring', 'Chronic conditions'),
  ('E78.6', 'Chronic metabolic diseases', 'high', 'Lipoprotein deficiency requires ongoing care', 'Chronic conditions'),
  ('E79.1', 'Chronic metabolic diseases', 'medium', 'Lesch-Nyhan syndrome requires regular monitoring', 'Chronic conditions'),
  ('E79.8', 'Chronic metabolic diseases', 'medium', 'Other disorders of purine and pyrimidine metabolism', 'Chronic conditions'),
  ('E79.9', 'Chronic metabolic diseases', 'medium', 'Disorder of purine and pyrimidine metabolism, unspecified', 'Chronic conditions'),
  ('E83.10', 'Chronic metabolic diseases', 'medium', 'Disorder of iron metabolism, unspecified', 'Chronic conditions'),
  ('E83.19', 'Chronic metabolic diseases', 'medium', 'Other disorders of iron metabolism', 'Chronic conditions'),
  ('E83.30', 'Chronic metabolic diseases', 'medium', 'Disorder of phosphorus metabolism, unspecified', 'Chronic conditions'),
  ('E83.31', 'Chronic metabolic diseases', 'medium', 'Familial hypophosphatemia', 'Chronic conditions'),
  ('E83.32', 'Chronic metabolic diseases', 'medium', 'Hereditary vitamin D-dependent rickets', 'Chronic conditions'),
  ('E83.39', 'Chronic metabolic diseases', 'medium', 'Other disorders of phosphorus metabolism', 'Chronic conditions'),
  ('E83.40', 'Chronic metabolic diseases', 'medium', 'Disorders of magnesium metabolism, unspecified', 'Chronic conditions'),
  ('E83.41', 'Chronic metabolic diseases', 'medium', 'Hypermagnesemia', 'Chronic conditions'),
  ('E83.42', 'Chronic metabolic diseases', 'medium', 'Hypomagnesemia', 'Chronic conditions'),
  ('E83.49', 'Chronic metabolic diseases', 'medium', 'Other disorders of magnesium metabolism', 'Chronic conditions'),
  ('E83.50', 'Chronic metabolic diseases', 'medium', 'Unspecified disorder of calcium metabolism', 'Chronic conditions'),
  ('E83.52', 'Chronic metabolic diseases', 'medium', 'Hypercalcemia', 'Chronic conditions'),
  ('E83.59', 'Chronic metabolic diseases', 'medium', 'Other disorders of calcium metabolism', 'Chronic conditions'),
  ('E83.81', 'Chronic metabolic diseases', 'medium', 'Hungry bone syndrome', 'Chronic conditions'),
  ('E83.89', 'Chronic metabolic diseases', 'medium', 'Other disorders of mineral metabolism', 'Chronic conditions'),
  ('E83.9', 'Chronic metabolic diseases', 'medium', 'Disorder of mineral metabolism, unspecified', 'Chronic conditions'),
  ('E85.9', 'Chronic metabolic diseases', 'medium', 'Amyloidosis, unspecified', 'Chronic conditions'),
  ('E86.0', 'Chronic metabolic diseases', 'high', 'Dehydration requires monitoring', 'Chronic conditions'),
  ('E86.1', 'Chronic metabolic diseases', 'high', 'Hypovolemia requires regular monitoring', 'Chronic conditions'),
  ('E86.9', 'Chronic metabolic diseases', 'high', 'Volume depletion, unspecified', 'Chronic conditions'),
  ('E87.0', 'Chronic metabolic diseases', 'high', 'Hyperosmolality and hypernatremia', 'Chronic conditions'),
  ('E87.1', 'Chronic metabolic diseases', 'high', 'Hypo-osmolality and hyponatremia', 'Chronic conditions'),
  ('E87.2', 'Chronic metabolic diseases', 'high', 'Acidosis requires regular monitoring', 'Chronic conditions'),

  -- Chronic respiratory diseases (40 codes)
  ('J40', 'Chronic respiratory diseases', 'high', 'Bronchitis, not specified as acute or chronic', 'Chronic conditions'),
  ('J41.1', 'Chronic respiratory diseases', 'high', 'Mucopurulent chronic bronchitis', 'Chronic conditions'),
  ('J41.8', 'Chronic respiratory diseases', 'high', 'Mixed simple and mucopurulent chronic bronchitis', 'Chronic conditions'),
  ('J44.0', 'Chronic respiratory diseases', 'high', 'COPD with acute lower respiratory infection', 'Chronic conditions'),
  ('J44.1', 'Chronic respiratory diseases', 'high', 'COPD with acute exacerbation', 'Chronic conditions'),
  ('J45.21', 'Chronic respiratory diseases', 'high', 'Mild intermittent asthma with status asthmaticus', 'Chronic conditions'),
  ('J45.22', 'Chronic respiratory diseases', 'high', 'Mild intermittent asthma with acute exacerbation', 'Chronic conditions'),
  ('J45.31', 'Chronic respiratory diseases', 'high', 'Mild persistent asthma with status asthmaticus', 'Chronic conditions'),
  ('J45.32', 'Chronic respiratory diseases', 'high', 'Mild persistent asthma with acute exacerbation', 'Chronic conditions'),
  ('J45.40', 'Chronic respiratory diseases', 'high', 'Moderate persistent asthma, uncomplicated', 'Chronic conditions'),
  ('J45.41', 'Chronic respiratory diseases', 'high', 'Moderate persistent asthma with status asthmaticus', 'Chronic conditions'),
  ('J45.42', 'Chronic respiratory diseases', 'high', 'Moderate persistent asthma with acute exacerbation', 'Chronic conditions'),
  ('J45.50', 'Chronic respiratory diseases', 'high', 'Severe persistent asthma, uncomplicated', 'Chronic conditions'),
  ('J45.51', 'Chronic respiratory diseases', 'high', 'Severe persistent asthma with status asthmaticus', 'Chronic conditions'),
  ('J45.52', 'Chronic respiratory diseases', 'high', 'Severe persistent asthma with acute exacerbation', 'Chronic conditions'),
  ('J45.901', 'Chronic respiratory diseases', 'high', 'Unspecified asthma with status asthmaticus', 'Chronic conditions'),
  ('J45.902', 'Chronic respiratory diseases', 'high', 'Unspecified asthma with acute exacerbation', 'Chronic conditions'),
  ('J45.990', 'Chronic respiratory diseases', 'high', 'Exercise induced bronchospasm', 'Chronic conditions'),
  ('J45.991', 'Chronic respiratory diseases', 'high', 'Cough variant asthma', 'Chronic conditions'),
  ('J45.998', 'Chronic respiratory diseases', 'high', 'Other asthma', 'Chronic conditions'),
  ('J47.0', 'Chronic respiratory diseases', 'high', 'Bronchiectasis with acute exacerbation', 'Chronic conditions'),
  ('J47.1', 'Chronic respiratory diseases', 'high', 'Bronchiectasis with acute lower respiratory infection', 'Chronic conditions'),
  ('J47.9', 'Chronic respiratory diseases', 'high', 'Bronchiectasis, uncomplicated', 'Chronic conditions'),
  ('J60', 'Chronic respiratory diseases', 'high', 'Coalworker pneumoconiosis', 'Chronic conditions'),
  ('J61', 'Chronic respiratory diseases', 'high', 'Pneumoconiosis due to asbestos and other mineral fibers', 'Chronic conditions'),
  ('J62.0', 'Chronic respiratory diseases', 'high', 'Pneumoconiosis due to talc dust', 'Chronic conditions'),
  ('J62.8', 'Chronic respiratory diseases', 'high', 'Pneumoconiosis due to other dust containing silica', 'Chronic conditions'),
  ('J63.0', 'Chronic respiratory diseases', 'high', 'Aluminosis (of lung)', 'Chronic conditions'),
  ('J63.1', 'Chronic respiratory diseases', 'high', 'Bauxite fibrosis (of lung)', 'Chronic conditions'),
  ('J63.2', 'Chronic respiratory diseases', 'high', 'Berylliosis', 'Chronic conditions'),
  ('J63.3', 'Chronic respiratory diseases', 'high', 'Graphite fibrosis (of lung)', 'Chronic conditions'),
  ('J63.4', 'Chronic respiratory diseases', 'high', 'Siderosis', 'Chronic conditions'),
  ('J63.5', 'Chronic respiratory diseases', 'high', 'Stannosis', 'Chronic conditions'),
  ('J63.6', 'Chronic respiratory diseases', 'high', 'Pneumoconiosis due to other specified inorganic dusts', 'Chronic conditions'),
  ('J64', 'Chronic respiratory diseases', 'high', 'Unspecified pneumoconiosis', 'Chronic conditions'),
  ('J65', 'Chronic respiratory diseases', 'high', 'Pneumoconiosis associated with tuberculosis', 'Chronic conditions'),
  ('J66.0', 'Chronic respiratory diseases', 'high', 'Byssinosis', 'Chronic conditions'),
  ('J66.1', 'Chronic respiratory diseases', 'high', 'Flax-dressers disease', 'Chronic conditions'),
  ('J66.2', 'Chronic respiratory diseases', 'high', 'Cannabinosis', 'Chronic conditions'),
  ('J66.8', 'Chronic respiratory diseases', 'high', 'Airway disease due to other specific organic dusts', 'Chronic conditions'),

  -- Complex condition / Frail elderly (40 codes)
  ('R26.0', 'Complex condition / Frail elderly', 'high', 'Ataxic gait requires monitoring', 'Complex, multi-morbid'),
  ('R26.1', 'Complex condition / Frail elderly', 'high', 'Paralytic gait requires ongoing support', 'Complex, multi-morbid'),
  ('R26.9', 'Complex condition / Frail elderly', 'high', 'Unspecified abnormalities of gait and mobility', 'Complex, multi-morbid'),
  ('R27.0', 'Complex condition / Frail elderly', 'high', 'Ataxia, unspecified', 'Complex, multi-morbid'),
  ('R27.8', 'Complex condition / Frail elderly', 'high', 'Other lack of coordination', 'Complex, multi-morbid'),
  ('R27.9', 'Complex condition / Frail elderly', 'high', 'Unspecified lack of coordination', 'Complex, multi-morbid'),
  ('R29.0', 'Complex condition / Frail elderly', 'high', 'Tetany', 'Complex, multi-morbid'),
  ('R29.1', 'Complex condition / Frail elderly', 'high', 'Meningismus', 'Complex, multi-morbid'),
  ('R29.2', 'Complex condition / Frail elderly', 'high', 'Abnormal reflex', 'Complex, multi-morbid'),
  ('R29.3', 'Complex condition / Frail elderly', 'high', 'Abnormal posture', 'Complex, multi-morbid'),
  ('R29.4', 'Complex condition / Frail elderly', 'high', 'Clicking hip', 'Complex, multi-morbid'),
  ('R29.5', 'Complex condition / Frail elderly', 'high', 'Transient paralysis', 'Complex, multi-morbid'),
  ('R29.6', 'Complex condition / Frail elderly', 'high', 'Repeated falls', 'Complex, multi-morbid'),
  ('R29.810', 'Complex condition / Frail elderly', 'high', 'Facial weakness', 'Complex, multi-morbid'),
  ('R29.818', 'Complex condition / Frail elderly', 'high', 'Other symptoms and signs involving the nervous system', 'Complex, multi-morbid'),
  ('R29.890', 'Complex condition / Frail elderly', 'high', 'Loss of height', 'Complex, multi-morbid'),
  ('R29.891', 'Complex condition / Frail elderly', 'high', 'Ocular torticollis', 'Complex, multi-morbid'),
  ('R29.898', 'Complex condition / Frail elderly', 'high', 'Other symptoms and signs involving the musculoskeletal system', 'Complex, multi-morbid'),
  ('R29.90', 'Complex condition / Frail elderly', 'high', 'Unspecified symptoms and signs involving the nervous system', 'Complex, multi-morbid'),
  ('R29.91', 'Complex condition / Frail elderly', 'high', 'Unspecified symptoms and signs involving the musculoskeletal system', 'Complex, multi-morbid'),
  ('R41.0', 'Complex condition / Frail elderly', 'high', 'Disorientation, unspecified', 'Complex, multi-morbid'),
  ('R41.1', 'Complex condition / Frail elderly', 'high', 'Anterograde amnesia', 'Complex, multi-morbid'),
  ('R41.2', 'Complex condition / Frail elderly', 'high', 'Retrograde amnesia', 'Complex, multi-morbid'),
  ('R41.4', 'Complex condition / Frail elderly', 'high', 'Neurologic neglect syndrome', 'Complex, multi-morbid'),
  ('R41.82', 'Complex condition / Frail elderly', 'high', 'Altered mental status, unspecified', 'Complex, multi-morbid'),
  ('R41.83', 'Complex condition / Frail elderly', 'high', 'Borderline intellectual functioning', 'Complex, multi-morbid'),
  ('R41.840', 'Complex condition / Frail elderly', 'high', 'Attention and concentration deficit', 'Complex, multi-morbid'),
  ('R41.841', 'Complex condition / Frail elderly', 'high', 'Cognitive communication deficit', 'Complex, multi-morbid'),
  ('R41.842', 'Complex condition / Frail elderly', 'high', 'Visuospatial deficit', 'Complex, multi-morbid'),
  ('R41.843', 'Complex condition / Frail elderly', 'high', 'Psychomotor deficit', 'Complex, multi-morbid'),
  ('R41.844', 'Complex condition / Frail elderly', 'high', 'Frontal lobe and executive function deficit', 'Complex, multi-morbid'),
  ('R41.89', 'Complex condition / Frail elderly', 'high', 'Other symptoms and signs involving cognitive functions', 'Complex, multi-morbid'),
  ('R41.9', 'Complex condition / Frail elderly', 'high', 'Unspecified symptoms and signs involving cognitive functions', 'Complex, multi-morbid'),
  ('R42', 'Complex condition / Frail elderly', 'high', 'Dizziness and giddiness', 'Complex, multi-morbid'),
  ('R43.0', 'Complex condition / Frail elderly', 'high', 'Anosmia', 'Complex, multi-morbid'),
  ('R43.1', 'Complex condition / Frail elderly', 'high', 'Parosmia', 'Complex, multi-morbid'),
  ('R43.2', 'Complex condition / Frail elderly', 'high', 'Parageusia', 'Complex, multi-morbid'),
  ('R43.8', 'Complex condition / Frail elderly', 'high', 'Other disturbances of smell and taste', 'Complex, multi-morbid'),
  ('R43.9', 'Complex condition / Frail elderly', 'high', 'Unspecified disturbances of smell and taste', 'Complex, multi-morbid'),
  ('R45.1', 'Complex condition / Frail elderly', 'high', 'Restlessness and agitation', 'Complex, multi-morbid'),

  -- Allied Health & Health Promotion (40 codes)
  ('Z71.6', 'Allied Health & Health Promotion', 'high', 'Tobacco abuse counseling', 'Planned care'),
  ('Z71.7', 'Allied Health & Health Promotion', 'high', 'Human immunodeficiency virus counseling', 'Planned care'),
  ('Z71.81', 'Allied Health & Health Promotion', 'high', 'Spiritual or religious counseling', 'Planned care'),
  ('Z71.83', 'Allied Health & Health Promotion', 'high', 'Encounter for nonprocreative genetic counseling', 'Planned care'),
  ('Z71.84', 'Allied Health & Health Promotion', 'high', 'Encounter for health counseling related to travel', 'Planned care'),
  ('Z71.85', 'Allied Health & Health Promotion', 'high', 'Encounter for immunization safety counseling', 'Planned care'),
  ('Z71.87', 'Allied Health & Health Promotion', 'high', 'Encounter for pediatric-to-adult transition counseling', 'Planned care'),
  ('Z71.88', 'Allied Health & Health Promotion', 'high', 'Encounter for counseling for socioeconomic factors', 'Planned care'),
  ('Z72.0', 'Allied Health & Health Promotion', 'high', 'Tobacco use', 'Planned care'),
  ('Z72.1', 'Allied Health & Health Promotion', 'high', 'Alcohol use', 'Planned care'),
  ('Z72.2', 'Allied Health & Health Promotion', 'high', 'Drug use', 'Planned care'),
  ('Z72.3', 'Allied Health & Health Promotion', 'high', 'Lack of physical exercise', 'Planned care'),
  ('Z72.4', 'Allied Health & Health Promotion', 'high', 'Inappropriate diet and eating habits', 'Planned care'),
  ('Z72.51', 'Allied Health & Health Promotion', 'high', 'High risk heterosexual behavior', 'Planned care'),
  ('Z72.52', 'Allied Health & Health Promotion', 'high', 'High risk homosexual behavior', 'Planned care'),
  ('Z72.53', 'Allied Health & Health Promotion', 'high', 'High risk bisexual behavior', 'Planned care'),
  ('Z72.6', 'Allied Health & Health Promotion', 'high', 'Gambling and betting', 'Planned care'),
  ('Z72.810', 'Allied Health & Health Promotion', 'high', 'Child and adolescent antisocial behavior', 'Planned care'),
  ('Z72.811', 'Allied Health & Health Promotion', 'high', 'Adult antisocial behavior', 'Planned care'),
  ('Z72.820', 'Allied Health & Health Promotion', 'high', 'Sleep deprivation', 'Planned care'),
  ('Z72.821', 'Allied Health & Health Promotion', 'high', 'Inadequate sleep hygiene', 'Planned care'),
  ('Z72.89', 'Allied Health & Health Promotion', 'high', 'Other problems related to lifestyle', 'Planned care'),
  ('Z72.9', 'Allied Health & Health Promotion', 'high', 'Problem related to lifestyle, unspecified', 'Planned care'),
  ('Z73.0', 'Allied Health & Health Promotion', 'high', 'Burn-out', 'Planned care'),
  ('Z73.1', 'Allied Health & Health Promotion', 'high', 'Type A behavior pattern', 'Planned care'),
  ('Z73.2', 'Allied Health & Health Promotion', 'high', 'Lack of relaxation and leisure', 'Planned care'),
  ('Z73.3', 'Allied Health & Health Promotion', 'high', 'Stress, not elsewhere classified', 'Planned care'),
  ('Z73.4', 'Allied Health & Health Promotion', 'high', 'Inadequate social skills, not elsewhere classified', 'Planned care'),
  ('Z73.5', 'Allied Health & Health Promotion', 'high', 'Social role conflict, not elsewhere classified', 'Planned care'),
  ('Z73.6', 'Allied Health & Health Promotion', 'high', 'Limitation of activities due to disability', 'Planned care'),
  ('Z73.810', 'Allied Health & Health Promotion', 'high', 'Behavioral insomnia of childhood, sleep-onset association type', 'Planned care'),
  ('Z73.811', 'Allied Health & Health Promotion', 'high', 'Behavioral insomnia of childhood, limit setting type', 'Planned care'),
  ('Z73.812', 'Allied Health & Health Promotion', 'high', 'Behavioral insomnia of childhood, combined type', 'Planned care'),
  ('Z73.819', 'Allied Health & Health Promotion', 'high', 'Behavioral insomnia of childhood, unspecified type', 'Planned care'),
  ('Z73.82', 'Allied Health & Health Promotion', 'high', 'Dual sensory impairment', 'Planned care'),
  ('Z73.89', 'Allied Health & Health Promotion', 'high', 'Other problems related to life management difficulty', 'Planned care'),
  ('Z73.9', 'Allied Health & Health Promotion', 'high', 'Problem related to life management difficulty, unspecified', 'Planned care'),
  ('Z76.81', 'Allied Health & Health Promotion', 'high', 'Expectant parent preparation classes', 'Planned care'),
  ('Z76.89', 'Allied Health & Health Promotion', 'high', 'Persons encountering health services in other specified circumstances', 'Planned care'),
  ('Z76.9', 'Allied Health & Health Promotion', 'high', 'Persons encountering health services in unspecified circumstances', 'Planned care');

-- Add corresponding entries to home_codes if they don't exist
INSERT INTO home_codes ("Care Setting", "Systems of Care", "ICD FamilyCode")
SELECT 
    'HOME',
    systems_of_care,
    icd_code
FROM home_services_mapping
WHERE NOT EXISTS (
    SELECT 1 FROM home_codes WHERE "ICD FamilyCode" = home_services_mapping.icd_code
)
ON CONFLICT DO NOTHING;