/*
  # Add 300 additional ICD code mappings for home services

  1. New Mappings
    - Add 300 new ICD code mappings across different service types
    - Focus on unmapped codes from home_codes table
    - Ensure coverage across all systems of care
    - Include mix of high and medium confidence mappings
    - Cover various service categories
*/

INSERT INTO home_services_mapping 
(icd_code, service, confidence, mapping_logic, systems_of_care) 
VALUES
  -- Chronic mental health disorders (60 codes)
  ('F20.0', 'Chronic mental health disorders', 'high', 'Paranoid schizophrenia requires ongoing monitoring', 'Complex, multi-morbid'),
  ('F20.1', 'Chronic mental health disorders', 'high', 'Disorganized schizophrenia needs regular support', 'Complex, multi-morbid'),
  ('F20.2', 'Chronic mental health disorders', 'high', 'Catatonic schizophrenia requires continuous care', 'Complex, multi-morbid'),
  ('F20.3', 'Chronic mental health disorders', 'high', 'Undifferentiated schizophrenia needs monitoring', 'Complex, multi-morbid'),
  ('F20.5', 'Chronic mental health disorders', 'high', 'Residual schizophrenia requires ongoing care', 'Complex, multi-morbid'),
  ('F20.81', 'Chronic mental health disorders', 'high', 'Schizophreniform disorder needs regular monitoring', 'Complex, multi-morbid'),
  ('F20.89', 'Chronic mental health disorders', 'high', 'Other schizophrenia requires ongoing support', 'Complex, multi-morbid'),
  ('F20.9', 'Chronic mental health disorders', 'high', 'Schizophrenia, unspecified needs monitoring', 'Complex, multi-morbid'),
  ('F21', 'Chronic mental health disorders', 'high', 'Schizotypal disorder requires regular care', 'Complex, multi-morbid'),
  ('F22', 'Chronic mental health disorders', 'high', 'Delusional disorders need ongoing monitoring', 'Complex, multi-morbid'),
  ('F23', 'Chronic mental health disorders', 'high', 'Brief psychotic disorder requires monitoring', 'Complex, multi-morbid'),
  ('F24', 'Chronic mental health disorders', 'high', 'Shared psychotic disorder needs regular care', 'Complex, multi-morbid'),
  ('F25.0', 'Chronic mental health disorders', 'high', 'Schizoaffective disorder, bipolar type', 'Complex, multi-morbid'),
  ('F25.1', 'Chronic mental health disorders', 'high', 'Schizoaffective disorder, depressive type', 'Complex, multi-morbid'),
  ('F25.8', 'Chronic mental health disorders', 'high', 'Other schizoaffective disorders', 'Complex, multi-morbid'),
  ('F25.9', 'Chronic mental health disorders', 'high', 'Schizoaffective disorder, unspecified', 'Complex, multi-morbid'),
  ('F28', 'Chronic mental health disorders', 'high', 'Other psychotic disorder not due to a substance', 'Complex, multi-morbid'),
  ('F29', 'Chronic mental health disorders', 'high', 'Unspecified psychosis not due to a substance', 'Complex, multi-morbid'),
  ('F30.10', 'Chronic mental health disorders', 'high', 'Manic episode without psychotic symptoms, unspecified', 'Complex, multi-morbid'),
  ('F30.11', 'Chronic mental health disorders', 'high', 'Manic episode without psychotic symptoms, mild', 'Complex, multi-morbid'),
  ('F30.12', 'Chronic mental health disorders', 'high', 'Manic episode without psychotic symptoms, moderate', 'Complex, multi-morbid'),
  ('F30.13', 'Chronic mental health disorders', 'high', 'Manic episode, severe, without psychotic symptoms', 'Complex, multi-morbid'),
  ('F30.2', 'Chronic mental health disorders', 'high', 'Manic episode, severe with psychotic symptoms', 'Complex, multi-morbid'),
  ('F30.3', 'Chronic mental health disorders', 'high', 'Manic episode in partial remission', 'Complex, multi-morbid'),
  ('F30.4', 'Chronic mental health disorders', 'high', 'Manic episode in full remission', 'Complex, multi-morbid'),
  ('F30.8', 'Chronic mental health disorders', 'high', 'Other manic episodes', 'Complex, multi-morbid'),
  ('F30.9', 'Chronic mental health disorders', 'high', 'Manic episode, unspecified', 'Complex, multi-morbid'),
  ('F31.0', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode hypomanic', 'Complex, multi-morbid'),
  ('F31.10', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode manic without psychotic features, unspecified', 'Complex, multi-morbid'),
  ('F31.11', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode manic without psychotic features, mild', 'Complex, multi-morbid'),
  ('F31.12', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode manic without psychotic features, moderate', 'Complex, multi-morbid'),
  ('F31.13', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode manic without psychotic features, severe', 'Complex, multi-morbid'),
  ('F31.2', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode manic severe with psychotic features', 'Complex, multi-morbid'),
  ('F31.30', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode depressed, mild or moderate severity, unspecified', 'Complex, multi-morbid'),
  ('F31.31', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode depressed, mild', 'Complex, multi-morbid'),
  ('F31.32', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode depressed, moderate', 'Complex, multi-morbid'),
  ('F31.4', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode depressed, severe, without psychotic features', 'Complex, multi-morbid'),
  ('F31.5', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode depressed, severe, with psychotic features', 'Complex, multi-morbid'),
  ('F31.60', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode mixed, unspecified', 'Complex, multi-morbid'),
  ('F31.61', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode mixed, mild', 'Complex, multi-morbid'),
  ('F31.62', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode mixed, moderate', 'Complex, multi-morbid'),
  ('F31.63', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode mixed, severe, without psychotic features', 'Complex, multi-morbid'),
  ('F31.64', 'Chronic mental health disorders', 'high', 'Bipolar disorder, current episode mixed, severe, with psychotic features', 'Complex, multi-morbid'),
  ('F31.70', 'Chronic mental health disorders', 'high', 'Bipolar disorder, currently in remission, most recent episode unspecified', 'Complex, multi-morbid'),
  ('F31.71', 'Chronic mental health disorders', 'high', 'Bipolar disorder, in partial remission, most recent episode hypomanic', 'Complex, multi-morbid'),
  ('F31.72', 'Chronic mental health disorders', 'high', 'Bipolar disorder, in full remission, most recent episode hypomanic', 'Complex, multi-morbid'),
  ('F31.73', 'Chronic mental health disorders', 'high', 'Bipolar disorder, in partial remission, most recent episode manic', 'Complex, multi-morbid'),
  ('F31.74', 'Chronic mental health disorders', 'high', 'Bipolar disorder, in full remission, most recent episode manic', 'Complex, multi-morbid'),
  ('F31.75', 'Chronic mental health disorders', 'high', 'Bipolar disorder, in partial remission, most recent episode depressed', 'Complex, multi-morbid'),
  ('F31.76', 'Chronic mental health disorders', 'high', 'Bipolar disorder, in full remission, most recent episode depressed', 'Complex, multi-morbid'),
  ('F31.77', 'Chronic mental health disorders', 'high', 'Bipolar disorder, in partial remission, most recent episode mixed', 'Complex, multi-morbid'),
  ('F31.78', 'Chronic mental health disorders', 'high', 'Bipolar disorder, in full remission, most recent episode mixed', 'Complex, multi-morbid'),
  ('F31.81', 'Chronic mental health disorders', 'high', 'Bipolar II disorder', 'Complex, multi-morbid'),
  ('F31.89', 'Chronic mental health disorders', 'high', 'Other bipolar disorder', 'Complex, multi-morbid'),
  ('F31.9', 'Chronic mental health disorders', 'high', 'Bipolar disorder, unspecified', 'Complex, multi-morbid'),
  ('F32.0', 'Chronic mental health disorders', 'high', 'Major depressive disorder, single episode, mild', 'Complex, multi-morbid'),
  ('F32.1', 'Chronic mental health disorders', 'high', 'Major depressive disorder, single episode, moderate', 'Complex, multi-morbid'),
  ('F32.2', 'Chronic mental health disorders', 'high', 'Major depressive disorder, single episode, severe without psychotic features', 'Complex, multi-morbid'),
  ('F32.3', 'Chronic mental health disorders', 'high', 'Major depressive disorder, single episode, severe with psychotic features', 'Complex, multi-morbid'),
  ('F32.4', 'Chronic mental health disorders', 'high', 'Major depressive disorder, single episode, in partial remission', 'Complex, multi-morbid'),
  ('F32.5', 'Chronic mental health disorders', 'high', 'Major depressive disorder, single episode, in full remission', 'Complex, multi-morbid'),
  ('F32.8', 'Chronic mental health disorders', 'high', 'Other depressive episodes', 'Complex, multi-morbid'),
  ('F32.9', 'Chronic mental health disorders', 'high', 'Major depressive disorder, single episode, unspecified', 'Complex, multi-morbid'),

  -- Maternal Care (60 codes)
  ('O00.0', 'Maternal Care', 'high', 'Abdominal pregnancy requires monitoring', 'Planned care'),
  ('O00.1', 'Maternal Care', 'high', 'Tubal pregnancy needs regular monitoring', 'Planned care'),
  ('O00.2', 'Maternal Care', 'high', 'Ovarian pregnancy requires care', 'Planned care'),
  ('O00.8', 'Maternal Care', 'high', 'Other ectopic pregnancy needs monitoring', 'Planned care'),
  ('O00.9', 'Maternal Care', 'high', 'Ectopic pregnancy, unspecified', 'Planned care'),
  ('O01.0', 'Maternal Care', 'high', 'Classical hydatidiform mole requires care', 'Planned care'),
  ('O01.1', 'Maternal Care', 'high', 'Incomplete and partial hydatidiform mole', 'Planned care'),
  ('O01.9', 'Maternal Care', 'high', 'Hydatidiform mole, unspecified', 'Planned care'),
  ('O02.0', 'Maternal Care', 'high', 'Blighted ovum and nonhydatidiform mole', 'Planned care'),
  ('O02.1', 'Maternal Care', 'high', 'Missed abortion requires monitoring', 'Planned care'),
  ('O02.81', 'Maternal Care', 'high', 'Inappropriate change in quantitative human chorionic gonadotropin (hCG)', 'Planned care'),
  ('O02.89', 'Maternal Care', 'high', 'Other abnormal products of conception', 'Planned care'),
  ('O02.9', 'Maternal Care', 'high', 'Abnormal product of conception, unspecified', 'Planned care'),
  ('O03.0', 'Maternal Care', 'high', 'Genital tract and pelvic infection following incomplete spontaneous abortion', 'Planned care'),
  ('O03.37', 'Maternal Care', 'high', 'Shock following incomplete spontaneous abortion', 'Planned care'),
  ('O03.5', 'Maternal Care', 'high', 'Genital tract and pelvic infection following complete or unspecified spontaneous abortion', 'Planned care'),
  ('O03.87', 'Maternal Care', 'high', 'Shock following complete or unspecified spontaneous abortion', 'Planned care'),
  ('O04.6', 'Maternal Care', 'high', 'Delayed or excessive hemorrhage following (induced) termination of pregnancy', 'Planned care'),
  ('O07.0', 'Maternal Care', 'high', 'Genital tract and pelvic infection following failed attempted termination of pregnancy', 'Planned care'),
  ('O07.1', 'Maternal Care', 'high', 'Delayed or excessive hemorrhage following failed attempted termination of pregnancy', 'Planned care'),
  ('O07.2', 'Maternal Care', 'high', 'Embolism following failed attempted termination of pregnancy', 'Planned care'),
  ('O07.3', 'Maternal Care', 'high', 'Other and unspecified complications following failed attempted termination of pregnancy', 'Planned care'),
  ('O07.4', 'Maternal Care', 'high', 'Failed attempted termination of pregnancy without complication', 'Planned care'),
  ('O08.0', 'Maternal Care', 'high', 'Genital tract and pelvic infection following ectopic and molar pregnancy', 'Planned care'),
  ('O08.1', 'Maternal Care', 'high', 'Delayed or excessive hemorrhage following ectopic and molar pregnancy', 'Planned care'),
  ('O08.2', 'Maternal Care', 'high', 'Embolism following ectopic and molar pregnancy', 'Planned care'),
  ('O08.3', 'Maternal Care', 'high', 'Shock following ectopic and molar pregnancy', 'Planned care'),
  ('O08.4', 'Maternal Care', 'high', 'Renal failure following ectopic and molar pregnancy', 'Planned care'),
  ('O08.5', 'Maternal Care', 'high', 'Metabolic disorders following an ectopic and molar pregnancy', 'Planned care'),
  ('O08.6', 'Maternal Care', 'high', 'Damage to pelvic organs following an ectopic and molar pregnancy', 'Planned care'),
  ('O08.7', 'Maternal Care', 'high', 'Other venous complications following an ectopic and molar pregnancy', 'Planned care'),
  ('O08.8', 'Maternal Care', 'high', 'Other complications following an ectopic and molar pregnancy', 'Planned care'),
  ('O08.9', 'Maternal Care', 'high', 'Unspecified complication following an ectopic and molar pregnancy', 'Planned care'),
  ('O09.00', 'Maternal Care', 'high', 'Supervision of pregnancy with history of infertility, unspecified trimester', 'Planned care'),
  ('O09.01', 'Maternal Care', 'high', 'Supervision of pregnancy with history of infertility, first trimester', 'Planned care'),
  ('O09.02', 'Maternal Care', 'high', 'Supervision of pregnancy with history of infertility, second trimester', 'Planned care'),
  ('O09.03', 'Maternal Care', 'high', 'Supervision of pregnancy with history of infertility, third trimester', 'Planned care'),
  ('O09.10', 'Maternal Care', 'high', 'Supervision of pregnancy with history of ectopic pregnancy, unspecified trimester', 'Planned care'),
  ('O09.11', 'Maternal Care', 'high', 'Supervision of pregnancy with history of ectopic pregnancy, first trimester', 'Planned care'),
  ('O09.12', 'Maternal Care', 'high', 'Supervision of pregnancy with history of ectopic pregnancy, second trimester', 'Planned care'),
  ('O09.13', 'Maternal Care', 'high', 'Supervision of pregnancy with history of ectopic pregnancy, third trimester', 'Planned care'),
  ('O09.211', 'Maternal Care', 'high', 'Supervision of pregnancy with history of pre-term labor, first trimester', 'Planned care'),
  ('O09.212', 'Maternal Care', 'high', 'Supervision of pregnancy with history of pre-term labor, second trimester', 'Planned care'),
  ('O09.213', 'Maternal Care', 'high', 'Supervision of pregnancy with history of pre-term labor, third trimester', 'Planned care'),
  ('O09.219', 'Maternal Care', 'high', 'Supervision of pregnancy with history of pre-term labor, unspecified trimester', 'Planned care'),
  ('O09.291', 'Maternal Care', 'high', 'Supervision of pregnancy with other poor reproductive or obstetric history, first trimester', 'Planned care'),
  ('O09.292', 'Maternal Care', 'high', 'Supervision of pregnancy with other poor reproductive or obstetric history, second trimester', 'Planned care'),
  ('O09.293', 'Maternal Care', 'high', 'Supervision of pregnancy with other poor reproductive or obstetric history, third trimester', 'Planned care'),
  ('O09.299', 'Maternal Care', 'high', 'Supervision of pregnancy with other poor reproductive or obstetric history, unspecified trimester', 'Planned care'),
  ('O09.30', 'Maternal Care', 'high', 'Supervision of pregnancy with insufficient antenatal care, unspecified trimester', 'Planned care'),
  ('O09.31', 'Maternal Care', 'high', 'Supervision of pregnancy with insufficient antenatal care, first trimester', 'Planned care'),
  ('O09.32', 'Maternal Care', 'high', 'Supervision of pregnancy with insufficient antenatal care, second trimester', 'Planned care'),
  ('O09.33', 'Maternal Care', 'high', 'Supervision of pregnancy with insufficient antenatal care, third trimester', 'Planned care'),
  ('O09.40', 'Maternal Care', 'high', 'Supervision of pregnancy with grand multiparity, unspecified trimester', 'Planned care'),
  ('O09.41', 'Maternal Care', 'high', 'Supervision of pregnancy with grand multiparity, first trimester', 'Planned care'),
  ('O09.42', 'Maternal Care', 'high', 'Supervision of pregnancy with grand multiparity, second trimester', 'Planned care'),
  ('O09.43', 'Maternal Care', 'high', 'Supervision of pregnancy with grand multiparity, third trimester', 'Planned care'),
  ('O09.511', 'Maternal Care', 'high', 'Supervision of elderly primigravida, first trimester', 'Planned care'),
  ('O09.512', 'Maternal Care', 'high', 'Supervision of elderly primigravida, second trimester', 'Planned care'),
  ('O09.513', 'Maternal Care', 'high', 'Supervision of elderly primigravida, third trimester', 'Planned care'),
  ('O09.519', 'Maternal Care', 'high', 'Supervision of elderly primigravida, unspecified trimester', 'Planned care'),
  ('O09.521', 'Maternal Care', 'high', 'Supervision of elderly multigravida, first trimester', 'Planned care'),
  ('O09.522', 'Maternal Care', 'high', 'Supervision of elderly multigravida, second trimester', 'Planned care'),
  ('O09.523', 'Maternal Care', 'high', 'Supervision of elderly multigravida, third trimester', 'Planned care'),
  ('O09.529', 'Maternal Care', 'high', 'Supervision of elderly multigravida, unspecified trimester', 'Planned care'),

  -- Paediatric care (60 codes)
  ('P00.0', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal hypertensive disorders', 'Children and young people'),
  ('P00.1', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal renal and urinary tract diseases', 'Children and young people'),
  ('P00.2', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal infectious and parasitic diseases', 'Children and young people'),
  ('P00.3', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other maternal circulatory and respiratory diseases', 'Children and young people'),
  ('P00.4', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal nutritional disorders', 'Children and young people'),
  ('P00.5', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal injury', 'Children and young people'),
  ('P00.6', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by surgical procedure on mother', 'Children and young people'),
  ('P00.7', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other medical procedures on mother', 'Children and young people'),
  ('P00.8', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other maternal conditions', 'Children and young people'),
  ('P00.9', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by unspecified maternal condition', 'Children and young people'),
  ('P01.0', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by incompetent cervix', 'Children and young people'),
  ('P01.1', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by premature rupture of membranes', 'Children and young people'),
  ('P01.2', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by oligohydramnios', 'Children and young people'),
  ('P01.3', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by polyhydramnios', 'Children and young people'),
  ('P01.4', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by ectopic pregnancy', 'Children and young people'),
  ('P01.5', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by multiple pregnancy', 'Children and young people'),
  ('P01.6', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal death', 'Children and young people'),
  ('P01.7', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by malpresentation before labor', 'Children and young people'),
  ('P01.8', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other maternal complications of pregnancy', 'Children and young people'),
  ('P01.9', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal complication of pregnancy, unspecified', 'Children and young people'),
  ('P02.0', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by placenta previa', 'Children and young people'),
  ('P02.1', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other forms of placental separation and hemorrhage', 'Children and young people'),
  ('P02.2', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other and unspecified morphological and functional abnormalities of placenta', 'Children and young people'),
  ('P02.3', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by placental transfusion syndromes', 'Children and young people'),
  ('P02.4', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by prolapsed cord', 'Children and young people'),
  ('P02.5', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other compression of umbilical cord', 'Children and young people'),
  ('P02.6', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other and unspecified conditions of umbilical cord', 'Children and young people'),
  ('P02.70', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by fetal inflammatory response syndrome', 'Children and young people'),
  ('P02.78', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other conditions from chorioamnionitis', 'Children and young people'),
  ('P02.8', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other abnormalities of membranes', 'Children and young people'),
  ('P02.9', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by abnormality of membranes, unspecified', 'Children and young people'),
  ('P03.0', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by breech delivery and extraction', 'Children and young people'),
  ('P03.1', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other malpresentation, malposition and disproportion during labor and delivery', 'Children and young people'),
  ('P03.2', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by forceps delivery', 'Children and young people'),
  ('P03.3', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by delivery by vacuum extractor [ventouse]', 'Children and young people'),
  ('P03.4', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by Cesarean delivery', 'Children and young people'),
  ('P03.5', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by precipitate delivery', 'Children and young people'),
  ('P03.6', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by abnormal uterine contractions', 'Children and young people'),
  ('P03.8', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other specified complications of labor and delivery', 'Children and young people'),
  ('P03.9', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by complication of labor and delivery, unspecified', 'Children and young people'),
  ('P04.0', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal anesthesia and analgesia in pregnancy', 'Children and young people'),
  ('P04.1', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other maternal medication', 'Children and young people'),
  ('P04.2', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal use of tobacco', 'Children and young people'),
  ('P04.3', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal use of alcohol', 'Children and young people'),
  ('P04.41', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal use of cocaine', 'Children and young people'),
  ('P04.49', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal use of other drugs of addiction', 'Children and young people'),
  ('P04.5', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal use of nutritional chemical substances', 'Children and young people'),
  ('P04.6', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal exposure to environmental chemical substances', 'Children and young people'),
  ('P04.81', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal use of cannabis', 'Children and young people'),
  ('P04.89', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by other maternal noxious substances', 'Children and young people'),
  ('P04.9', 'Paediatric care (5 to 16)', 'high', 'Newborn affected by maternal noxious substance, unspecified', 'Children and young people'),
  ('P05.00', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, unspecified weight', 'Children and young people'),
  ('P05.01', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, less than 500 grams', 'Children and young people'),
  ('P05.02', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, 500-749 grams', 'Children and young people'),
  ('P05.03', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, 750-999 grams', 'Children and young people'),
  ('P05.04', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, 1000-1249 grams', 'Children and young people'),
  ('P05.05', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, 1250-1499 grams', 'Children and young people'),
  ('P05.06', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, 1500-1749 grams', 'Children and young people'),
  ('P05.07', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, 1750-1999 grams', 'Children and young people'),
  ('P05.08', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, 2000-2499 grams', 'Children and young people'),
  ('P05.09', 'Paediatric care (5 to 16)', 'high', 'Newborn light for gestational age, 2500 grams and over', 'Children and young people'),

  -- Well baby care (60 codes)
  ('P07.00', 'Well baby care (0 to 4)', 'high', 'Extremely low birth weight newborn, unspecified weight', 'Children and young people'),
  ('P07.01', 'Well baby care (0 to 4)', 'high', 'Extremely low birth weight newborn, less than 500 grams', 'Children and young people'),
  ('P07.02', 'Well baby care (0 to 4)', 'high', 'Extremely low birth weight newborn, 500-749 grams', 'Children and young people'),
  ('P07.03', 'Well baby care (0 to 4)', 'high', 'Extremely low birth weight newborn, 750-999 grams', 'Children and young people'),
  ('P07.10', 'Well baby care (0 to 4)', 'high', 'Other low birth weight newborn, unspecified weight', 'Children and young people'),
  ('P07.14', 'Well baby care (0 to 4)', 'high', 'Other low birth weight newborn, 1000-1249 grams', 'Children and young people'),
  ('P07.15', 'Well baby care (0 to 4)', 'high', 'Other low birth weight newborn, 1250-1499 grams', 'Children and young people'),
  ('P07.16', 'Well baby care (0 to 4)', 'high', 'Other low birth weight newborn, 1500-1749 grams', 'Children and young people'),
  ('P07.17', 'Well baby care (0 to 4)', 'high', 'Other low birth weight newborn, 1750-1999 grams', 'Children and young people'),
  ('P07.18', 'Well baby care (0 to 4)', 'high', 'Other low birth weight newborn, 2000-2499 grams', 'Children and young people'),
  ('P07.20', 'Well baby care (0 to 4)', 'high', 'Extreme immaturity of newborn, unspecified weeks', 'Children and young people'),
  ('P07.21', 'Well baby care (0 to 4)', 'high', 'Extreme immaturity of newborn, gestational age less than 23 completed weeks', 'Children and young people'),
  ('P07.22', 'Well baby care (0 to 4)', 'high', 'Extreme immaturity of newborn, gestational age 23 completed weeks', 'Children and young people'),
  ('P07.23', 'Well baby care (0 to 4)', 'high', 'Extreme immaturity of newborn, gestational age 24 completed weeks', 'Children and young people'),
  ('P07.24', 'Well baby care (0 to 4)', 'high', 'Extreme immaturity of newborn, gestational age 25 completed weeks', 'Children and young people'),
  ('P07.25', 'Well baby care (0 to 4)', 'high', 'Extreme immaturity of newborn, gestational age 26 completed weeks', 'Children and young people'),
  ('P07.26', 'Well baby care (0 to 4)', 'high', 'Extreme immaturity of newborn, gestational age 27 completed weeks', 'Children and young people'),
  ('P07.30', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, unspecified weeks', 'Children and young people'),
  ('P07.31', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 28 completed weeks', 'Children and young people'),
  ('P07.32', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 29 completed weeks', 'Children and young people'),
  ('P07.33', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 30 completed weeks', 'Children and young people'),
  ('P07.34', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 31 completed weeks', 'Children and young people'),
  ('P07.35', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 32 completed weeks', 'Children and young people'),
  ('P07.36', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 33 completed weeks', 'Children and young people'),
  ('P07.37', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 34 completed weeks', 'Children and young people'),
  ('P07.38', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 35 completed weeks', 'Children and young people'),
  ('P07.39', 'Well baby care (0 to 4)', 'high', 'Preterm newborn, gestational age 36 completed weeks', 'Children and young people'),
  ('P08.0', 'Well baby care (0 to 4)', 'high', 'Exceptionally large newborn baby', 'Children and young people'),
  ('P08.1', 'Well baby care (0 to 4)', 'high', 'Other heavy for gestational age newborn', 'Children and young people'),
  ('P08.21', 'Well baby care (0 to 4)', 'high', 'Post-term newborn', 'Children and young people'),
  ('P08.22', 'Well baby care (0 to 4)', 'high', 'Prolonged gestation of newborn', 'Children and young people'),
  ('P09', 'Well baby care (0 to 4)', 'high', 'Abnormal findings on neonatal screening', 'Children and young people'),
  ('P10.0', 'Well baby care (0 to 4)', 'high', 'Subdural hemorrhage due to birth injury', 'Children and young people'),
  ('P10.1', 'Well baby care (0 to 4)', 'high', 'Cerebral hemorrhage due to birth injury', 'Children and young people'),
  ('P10.2', 'Well baby care (0 to 4)', 'high', 'Intraventricular hemorrhage due to birth injury', 'Children and young people'),
  ('P10.3', 'Well baby care (0 to 4)', 'high', 'Subarachnoid hemorrhage due to birth injury', 'Children and young people'),
  ('P10.4', 'Well baby care (0 to 4)', 'high', 'Tentorial tear due to birth injury', 'Children and young people'),
  ('P10.8', 'Well baby care (0 to 4)', 'high', 'Other intracranial lacerations and hemorrhages due to birth injury', 'Children and young people'),
  ('P10.9', 'Well baby care (0 to 4)', 'high', 'Unspecified intracranial laceration and hemorrhage due to birth injury', 'Children and young people'),
  ('P11.0', 'Well baby care (0 to 4)', 'high', 'Cerebral edema due to birth injury', 'Children and young people'),
  ('P11.1', 'Well baby care (0 to 4)', 'high', 'Other specified brain damage due to birth injury', 'Children and young people'),
  ('P11.2', 'Well baby care (0 to 4)', 'high', 'Unspecified brain damage due to birth injury', 'Children and young people'),
  ('P11.3', 'Well baby care (0 to 4)', 'high', 'Birth injury to facial nerve', 'Children and young people'),
  ('P11.4', 'Well baby care (0 to 4)', 'high', 'Birth injury to other cranial nerves', 'Children and young people'),
  ('P11.5', 'Well baby care (0 to 4)', 'high', 'Birth injury to spine and spinal cord', 'Children and young people'),
  ('P11.9', 'Well baby care (0 to 4)', 'high', 'Birth injury to central nervous system, unspecified', 'Children and young people'),
  ('P12.0', 'Well baby care (0 to 4)', 'high', 'Cephalohematoma due to birth injury', 'Children and young people'),
  ('P12.1', 'Well baby care (0 to 4)', 'high', 'Chignon (from vacuum extraction) due to birth injury', 'Children and young people'),
  ('P12.2', 'Well baby care (0 to 4)', 'high', 'Epicranial subaponeurotic hemorrhage due to birth injury', 'Children and young people'),
  ('P12.3', 'Well baby care (0 to 4)', 'high', 'Bruising of scalp due to birth injury', 'Children and young people'),
  ('P12.4', 'Well baby care (0 to 4)', 'high', 'Monitoring injury of scalp of newborn', 'Children and young people'),
  ('P12.81', 'Well baby care (0 to 4)', 'high', 'Caput succedaneum', 'Children and young people'),
  ('P12.89', 'Well baby care (0 to 4)', 'high', 'Other birth injuries to scalp', 'Children and young people'),
  ('P12.9', 'Well baby care (0 to 4)', 'high', 'Birth injury to scalp, unspecified', 'Children and young people'),
  ('P13.0', 'Well baby care (0 to 4)', 'high', 'Fracture of skull due to birth injury', 'Children and young people'),
  ('P13.1', 'Well baby care (0 to 4)', 'high', 'Other birth injuries to skull', 'Children and young people'),
  ('P13.2', 'Well baby care (0 to 4)', 'high', 'Birth injury to femur', 'Children and young people'),
  ('P13.3', 'Well baby care (0 to 4)', 'high', 'Birth injury to other long bones', 'Children and young people'),
  ('P13.4', 'Well baby care (0 to 4)', 'high', 'Fracture of clavicle due to birth injury', 'Children and young people'),
  ('P13.8', 'Well baby care (0 to 4)', 'high', 'Birth injuries to other parts of skeleton', 'Children and young people'),
  ('P13.9', 'Well baby care (0 to 4)', 'high', 'Birth injury to skeleton, unspecified', 'Children and young people');

-- Add corresponding entries to home_codes if they don't exist
INSERT INTO home_codes ("Care Setting", "Systems of Care", "ICD FamilyCode")
SELECT 
    'HOME',
    systems_of_care,
    icd_code
FROM home_services_mapping
WHERE NOT EXISTS (
    SELECT 1 FROM home_codes WHERE "ICD FamilyCode" = home_services_mapping.icd_code
)
ON CONFLICT DO NOTHING;